"""A SQL Server key sequence must survive introspection and materialization.

``sys.identity_columns.seed_value`` is ``sql_variant``; pyodbc hands it back as
little-endian bytes, so ``int()`` raised and the swallowed error left the column
annotated as a plain ``BIGINT``. Every destination was then created with
``IDENTITY(1,1)`` under a table whose keys run 1000, 1010, 1020 — proven only by
reading the destination catalog, never by a row checksum.

The annotated carrier must also stay out of foreign DDL: ``BIGINT
IDENTITY(1000,10)`` pasted into PostgreSQL is a syntax error, and into Oracle a
LOB.
"""

from __future__ import annotations

from services.identity_carry import identity_generation, identity_seed_step
from services.schema_introspect import _as_int
from services.type_system import strip_identity_qualifier


def test_sql_variant_seed_bytes_are_decoded_not_dropped():
    assert _as_int(b"\xe8\x03\x00\x00\x00\x00\x00\x00", 1) == 1000
    assert _as_int(b"\n\x00\x00\x00\x00\x00\x00\x00", 1) == 10
    assert _as_int(b"\xff\xff\xff\xff\xff\xff\xff\xff", 1) == -1
    assert _as_int(7, 1) == 7
    # Unreadable stays the documented default rather than an invented number.
    assert _as_int(None, 1) == 1
    assert _as_int("not a number", 1) == 1


def test_annotated_carrier_yields_the_source_sequence():
    annotated = "BIGINT IDENTITY(1000,10)"
    assert identity_generation(annotated) == "by_default"
    assert identity_seed_step(annotated) == (1000, 10)


def test_generator_state_is_stripped_from_the_logical_carrier():
    # Storage is BIGINT; the sequence is generator state carried separately.
    assert strip_identity_qualifier("BIGINT IDENTITY(1000,10)") == "BIGINT"
    assert strip_identity_qualifier("INT IDENTITY") == "INT"
    assert (
        strip_identity_qualifier(
            "NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 5 INCREMENT BY 2)"
        )
        == "NUMBER"
    )
    # A column whose *name* or type merely contains the word is untouched.
    assert strip_identity_qualifier("VARCHAR(64)") == "VARCHAR(64)"
