"""PROPERTY 6 (identity RESTART) — the generator travels with the data.

AWS DMS copies identity *values* and leaves the destination sequence at 1.
Checksums stay green; the application's first INSERT without an explicit key
collides on PK or walks off a stepped progression (IDENTITY increment 10
resuming at max+1). DataFlow measures seed/increment from the source catalog,
emits them on CREATE, then forward-only-repairs the watermark and proves the
next INSERT lands on the source progression.
"""

from __future__ import annotations

import os
import socket
import sqlite3
import uuid
from pathlib import Path

import pytest

os.environ.setdefault("DATAFLOW_JOB_STORE", "memory")
os.environ.setdefault("DATAFLOW_DISABLE_OBJECT_STORE", "1")

from services.schema_introspect import introspect_schema
from src.transfer.engine import UniversalTransferEngine
from src.transfer.models import EndpointConfig, TransferRequest


def _run(req: TransferRequest):
    return UniversalTransferEngine().execute_tracked(req, uuid.uuid4().hex[:24])


def _pg_up() -> bool:
    try:
        with socket.create_connection(("127.0.0.1", 5432), timeout=0.4):
            return True
    except OSError:
        return False


def _mysql_up() -> bool:
    try:
        with socket.create_connection(("127.0.0.1", 3306), timeout=0.4):
            return True
    except OSError:
        return False


def _pg_creds() -> dict:
    return {
        "host": os.environ.get("P6_PG_HOST", os.environ.get("P2_PG_HOST", "127.0.0.1")),
        "port": int(os.environ.get("P6_PG_PORT", os.environ.get("P2_PG_PORT", "5432"))),
        "database": os.environ.get("P6_PG_DB", os.environ.get("P2_PG_DB", "dataflow")),
        "username": os.environ.get("P6_PG_USER", os.environ.get("P2_PG_USER", "dataflow")),
        "password": os.environ.get("P6_PG_PASSWORD", os.environ.get("P2_PG_PASSWORD", "dataflow")),
    }


def _mysql_creds() -> dict:
    return {
        "host": os.environ.get("P6_MYSQL_HOST", os.environ.get("P2_MYSQL_HOST", "127.0.0.1")),
        "port": int(os.environ.get("P6_MYSQL_PORT", os.environ.get("P2_MYSQL_PORT", "3306"))),
        "database": os.environ.get("P6_MYSQL_DB", os.environ.get("P2_MYSQL_DB", "dataflow")),
        "username": os.environ.get("P6_MYSQL_USER", os.environ.get("P2_MYSQL_USER", "dataflow")),
        "password": os.environ.get(
            "P6_MYSQL_PASSWORD", os.environ.get("P2_MYSQL_PASSWORD", "dataflow")
        ),
    }


def _identity_status(report: dict) -> set[str]:
    return {
        i["status"]
        for i in (report.get("items") or [])
        if i.get("aspect") == "identity_sequence"
    }


def _id_map():
    return {
        "source": "id",
        "target": "id",
        "source_type": "BIGINT",
        "target_type": "BIGINT",
        "approved": True,
        "confidence": 0.99,
    }


def _name_map():
    return {
        "source": "name",
        "target": "name",
        "source_type": "TEXT",
        "target_type": "TEXT",
        "approved": True,
        "confidence": 0.99,
    }


@pytest.mark.skipif(not _pg_up(), reason="PostgreSQL not listening on 5432")
def test_pg_stepped_identity_cutover_insert_lands_on_the_source_progression():
    """Source IDENTITY increment 10 must not resume as max+1 after load."""
    import psycopg2

    creds = _pg_creds()
    suffix = uuid.uuid4().hex[:8]
    src_table = f"p6_id_src_{suffix}"
    dst_table = f"p6_id_dst_{suffix}"
    conn = psycopg2.connect(
        host=creds["host"],
        port=creds["port"],
        dbname=creds["database"],
        user=creds["username"],
        password=creds["password"],
    )
    conn.autocommit = True
    try:
        with conn.cursor() as cur:
            cur.execute(f'DROP TABLE IF EXISTS public."{dst_table}"')
            cur.execute(f'DROP TABLE IF EXISTS public."{src_table}"')
            cur.execute(
                f'''
                CREATE TABLE public."{src_table}" (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY
                    (START WITH 5 INCREMENT BY 10) PRIMARY KEY,
                  name TEXT NOT NULL
                )
                '''
            )
            cur.execute(
                f'''INSERT INTO public."{src_table}" (name)
                    VALUES ('a'), ('b')'''
            )
            cur.execute(
                f'''INSERT INTO public."{src_table}" (id, name)
                    VALUES (100, 'explicit')'''
            )
    finally:
        conn.close()

    probed = introspect_schema(
        "postgresql",
        host=creds["host"],
        port=creds["port"],
        database=creds["database"],
        username=creds["username"],
        password=creds["password"],
        schema="public",
        table=src_table,
        ssl=False,
    )
    assert probed.get("ok"), probed
    src_id = {c["name"]: c for c in probed["columns"]}["id"]
    assert src_id["is_identity"] is True
    assert "START WITH 5" in str(src_id["inferred_type"]).upper()
    assert "INCREMENT BY 10" in str(src_id["inferred_type"]).upper()

    req = TransferRequest(
        source=EndpointConfig(
            kind="database",
            format="postgresql",
            host=creds["host"],
            port=creds["port"],
            database=creds["database"],
            username=creds["username"],
            password=creds["password"],
            schema="public",
            table=src_table,
            ssl=False,
        ),
        destination=EndpointConfig(
            kind="database",
            format="postgresql",
            host=creds["host"],
            port=creds["port"],
            database=creds["database"],
            username=creds["username"],
            password=creds["password"],
            schema="public",
            table=dst_table,
            ssl=False,
        ),
        mappings=[_id_map(), _name_map()],
        sync_mode="full_refresh_overwrite",
        validation_mode="warn",
        skip_preflight=True,
    )
    try:
        result = _run(req)
        assert result.success, result.error
        fid = (result.destination_summary or {}).get("schema_fidelity") or {}
        assert "carried" in _identity_status(fid), fid
        wm = (
            ((result.reconciliation or {}).get("physical_state") or {}).get(
                "identity_watermark"
            )
            or ((result.destination_summary or {}).get("physical_state") or {}).get(
                "identity_watermark"
            )
            or {}
        )
        checked = (wm.get("checked") or [{}])[0]
        if checked.get("available"):
            assert int(checked.get("increment") or 1) == 10, checked

        conn = psycopg2.connect(
            host=creds["host"],
            port=creds["port"],
            dbname=creds["database"],
            user=creds["username"],
            password=creds["password"],
        )
        try:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT s.seqstart, s.seqincrement
                      FROM pg_catalog.pg_class t
                      JOIN pg_catalog.pg_namespace n ON n.oid = t.relnamespace
                      JOIN pg_catalog.pg_attribute a ON a.attrelid = t.oid
                      JOIN pg_catalog.pg_depend d
                        ON d.refobjid = t.oid AND d.refobjsubid = a.attnum
                       AND d.classid = 'pg_class'::regclass
                       AND d.deptype IN ('a', 'i')
                      JOIN pg_catalog.pg_sequence s ON s.seqrelid = d.objid
                     WHERE n.nspname = 'public'
                       AND t.relname = %s
                       AND a.attname = 'id'
                    """,
                    (dst_table,),
                )
                row = cur.fetchone()
                assert row is not None, "destination has no owned identity sequence"
                assert int(row[1]) == 10, row
                cur.execute(
                    f'INSERT INTO public."{dst_table}" (name) VALUES (%s) RETURNING id',
                    ("cutover",),
                )
                next_id = cur.fetchone()[0]
                conn.commit()
                assert int(next_id) == 110, (
                    f"cutover INSERT returned {next_id}; stepped IDENTITY "
                    "must resume at 110 (max 100 + increment 10), not 101"
                )
        finally:
            conn.close()
    finally:
        conn = psycopg2.connect(
            host=creds["host"],
            port=creds["port"],
            dbname=creds["database"],
            user=creds["username"],
            password=creds["password"],
        )
        conn.autocommit = True
        try:
            with conn.cursor() as cur:
                cur.execute(f'DROP TABLE IF EXISTS public."{dst_table}"')
                cur.execute(f'DROP TABLE IF EXISTS public."{src_table}"')
        finally:
            conn.close()


@pytest.mark.skipif(not _mysql_up(), reason="MySQL/MariaDB not listening on 3306")
def test_mariadb_auto_increment_cutover_insert_does_not_collide():
    pymysql = pytest.importorskip("pymysql")

    creds = _mysql_creds()
    suffix = uuid.uuid4().hex[:8]
    src_table = f"p6_id_src_{suffix}"
    dst_table = f"p6_id_dst_{suffix}"
    conn = pymysql.connect(
        host=creds["host"],
        port=creds["port"],
        database=creds["database"],
        user=creds["username"],
        password=creds["password"],
        autocommit=True,
    )
    try:
        with conn.cursor() as cur:
            cur.execute(f"DROP TABLE IF EXISTS `{dst_table}`")
            cur.execute(f"DROP TABLE IF EXISTS `{src_table}`")
            cur.execute(
                f"""
                CREATE TABLE `{src_table}` (
                  id BIGINT NOT NULL AUTO_INCREMENT,
                  name VARCHAR(64) NOT NULL,
                  PRIMARY KEY (id)
                )
                """
            )
            cur.execute(
                f"INSERT INTO `{src_table}` (id, name) VALUES (1, 'a'), (2, 'b'), (50, 'explicit')"
            )
    finally:
        conn.close()

    req = TransferRequest(
        source=EndpointConfig(
            kind="database",
            format="mysql",
            host=creds["host"],
            port=creds["port"],
            database=creds["database"],
            username=creds["username"],
            password=creds["password"],
            schema="",
            table=src_table,
            ssl=False,
        ),
        destination=EndpointConfig(
            kind="database",
            format="mysql",
            host=creds["host"],
            port=creds["port"],
            database=creds["database"],
            username=creds["username"],
            password=creds["password"],
            schema="",
            table=dst_table,
            ssl=False,
        ),
        mappings=[
            _id_map(),
            {
                "source": "name",
                "target": "name",
                "source_type": "VARCHAR(64)",
                "target_type": "VARCHAR(64)",
                "approved": True,
                "confidence": 0.99,
            },
        ],
        sync_mode="full_refresh_overwrite",
        validation_mode="warn",
        skip_preflight=True,
    )
    try:
        result = _run(req)
        assert result.success, result.error
        fid = (result.destination_summary or {}).get("schema_fidelity") or {}
        assert "carried" in _identity_status(fid), fid

        conn = pymysql.connect(
            host=creds["host"],
            port=creds["port"],
            database=creds["database"],
            user=creds["username"],
            password=creds["password"],
            autocommit=True,
        )
        try:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT extra FROM information_schema.columns
                     WHERE table_schema = DATABASE()
                       AND table_name = %s AND column_name = 'id'
                    """,
                    (dst_table,),
                )
                extra = str((cur.fetchone() or [""])[0] or "").lower()
                assert "auto_increment" in extra, extra
                cur.execute(f"SELECT MAX(id) FROM `{dst_table}`")
                migrated_max = int(cur.fetchone()[0])
                cur.execute(f"INSERT INTO `{dst_table}` (name) VALUES ('cutover')")
                cur.execute("SELECT LAST_INSERT_ID()")
                nxt = int(cur.fetchone()[0])
                assert nxt > migrated_max, (
                    f"cutover INSERT returned {nxt} at or below migrated max {migrated_max}"
                )
        finally:
            conn.close()
    finally:
        conn = pymysql.connect(
            host=creds["host"],
            port=creds["port"],
            database=creds["database"],
            user=creds["username"],
            password=creds["password"],
            autocommit=True,
        )
        try:
            with conn.cursor() as cur:
                cur.execute(f"DROP TABLE IF EXISTS `{dst_table}`")
                cur.execute(f"DROP TABLE IF EXISTS `{src_table}`")
        finally:
            conn.close()


@pytest.mark.skipif(not _pg_up(), reason="PostgreSQL not listening on 5432")
def test_sqlite_autoincrement_is_carried_to_postgres_as_a_generator(tmp_path: Path):
    """SQLite AUTOINCREMENT must not land as a plain integer on PG."""
    import psycopg2

    creds = _pg_creds()
    src_path = tmp_path / "p6_id_src.db"
    src = sqlite3.connect(str(src_path))
    try:
        src.execute(
            "CREATE TABLE people (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL)"
        )
        src.execute("INSERT INTO people (name) VALUES ('a'), ('b')")
        src.execute("INSERT INTO people (id, name) VALUES (10, 'explicit')")
        src.commit()
    finally:
        src.close()

    probed = introspect_schema("sqlite", database=str(src_path), table="people")
    assert probed.get("ok"), probed
    src_id = {c["name"]: c for c in probed["columns"]}["id"]
    assert src_id["is_identity"] is True

    suffix = uuid.uuid4().hex[:8]
    dst_table = f"p6_id_sqlite_{suffix}"
    req = TransferRequest(
        source=EndpointConfig(
            kind="database",
            format="sqlite",
            database=str(src_path),
            table="people",
        ),
        destination=EndpointConfig(
            kind="database",
            format="postgresql",
            host=creds["host"],
            port=creds["port"],
            database=creds["database"],
            username=creds["username"],
            password=creds["password"],
            schema="public",
            table=dst_table,
            ssl=False,
        ),
        mappings=[_id_map(), _name_map()],
        sync_mode="full_refresh_overwrite",
        validation_mode="warn",
        skip_preflight=True,
    )
    try:
        result = _run(req)
        assert result.success, result.error
        fid = (result.destination_summary or {}).get("schema_fidelity") or {}
        assert "carried" in _identity_status(fid), fid

        conn = psycopg2.connect(
            host=creds["host"],
            port=creds["port"],
            dbname=creds["database"],
            user=creds["username"],
            password=creds["password"],
        )
        try:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT a.attidentity
                      FROM pg_catalog.pg_attribute a
                      JOIN pg_catalog.pg_class t ON t.oid = a.attrelid
                      JOIN pg_catalog.pg_namespace n ON n.oid = t.relnamespace
                     WHERE n.nspname = 'public'
                       AND t.relname = %s
                       AND a.attname = 'id'
                    """,
                    (dst_table,),
                )
                attidentity = (cur.fetchone() or [""])[0]
                assert str(attidentity or "").strip(), (
                    "sqlite AUTOINCREMENT did not create a PG identity generator"
                )
                cur.execute(
                    f'INSERT INTO public."{dst_table}" (name) VALUES (%s) RETURNING id',
                    ("cutover",),
                )
                next_id = int(cur.fetchone()[0])
                conn.commit()
                assert next_id > 10, next_id
        finally:
            conn.close()
    finally:
        conn = psycopg2.connect(
            host=creds["host"],
            port=creds["port"],
            dbname=creds["database"],
            user=creds["username"],
            password=creds["password"],
        )
        conn.autocommit = True
        try:
            with conn.cursor() as cur:
                cur.execute(f'DROP TABLE IF EXISTS public."{dst_table}"')
        finally:
            conn.close()
