"""An auto-increment default is not a fidelity collapse; a write restriction is.

``SERIAL``, ``AUTO_INCREMENT`` and ``GENERATED BY DEFAULT AS IDENTITY`` are
ordinary writable columns carrying a default. A destination without that default
accepts exactly the same values, so the transfer loses nothing — the missing
default is a DDL difference, reported by structure fidelity.

``GENERATED ALWAYS`` and SQL Server ``IDENTITY(seed, increment)`` are different:
they refuse client-supplied values, so mapping them onto a plain scalar hands
the operator a column that accepts writes the source forbade.
"""

from __future__ import annotations

import pytest

from services.identity_fit import (
    identity_polarity_would_collapse,
    identity_restricts_client_writes,
)
from services.type_system import is_lossy_coercion

WRITABLE_GENERATORS = [
    "SERIAL",
    "BIGSERIAL",
    "SMALLSERIAL",
    "INT AUTO_INCREMENT",
    "BIGINT AUTO_INCREMENT",
    "INT GENERATED BY DEFAULT AS IDENTITY",
]

RESTRICTED_GENERATORS = [
    "INT GENERATED ALWAYS AS IDENTITY",
    "NUMBER GENERATED ALWAYS AS IDENTITY",
    "IDENTITY(1,1)",
]

SCALAR_TARGETS = ["INTEGER", "BIGINT", "NUMBER(38,0)", "INT64", "long"]


@pytest.mark.parametrize("source", WRITABLE_GENERATORS)
def test_writable_generator_is_not_restricted(source: str):
    assert identity_restricts_client_writes(source) is False


@pytest.mark.parametrize("source", RESTRICTED_GENERATORS)
def test_restricted_generator_is_detected(source: str):
    assert identity_restricts_client_writes(source) is True


@pytest.mark.parametrize("source", WRITABLE_GENERATORS)
@pytest.mark.parametrize("target", SCALAR_TARGETS)
def test_auto_increment_pk_transfers_without_a_fidelity_block(
    source: str, target: str
):
    """The most common schema there is must not be blocked out of the box."""
    assert identity_polarity_would_collapse(source, target) is False
    assert is_lossy_coercion(source, target) is False


@pytest.mark.parametrize("source", RESTRICTED_GENERATORS)
@pytest.mark.parametrize("target", ["INTEGER", "BIGINT", "NUMBER(38,0)"])
def test_dropping_a_write_restriction_still_collapses(source: str, target: str):
    assert identity_polarity_would_collapse(source, target) is True
    assert is_lossy_coercion(source, target) is True


@pytest.mark.parametrize("source", RESTRICTED_GENERATORS)
def test_restriction_preserved_on_an_identity_target(source: str):
    assert (
        identity_polarity_would_collapse(
            source, "INTEGER GENERATED ALWAYS AS IDENTITY"
        )
        is False
    )
