"""Snowflake UNIQUE catalog + Oracle GENERATED/NLSSORT — enterprise SSOT."""

from __future__ import annotations

import sys
from pathlib import Path
from unittest.mock import MagicMock

_API_ROOT = Path(__file__).resolve().parents[1]
if str(_API_ROOT) not in sys.path:
    sys.path.insert(0, str(_API_ROOT))

from services.schema_introspect import _snowflake_fetch_unique_keys  # noqa: E402
from services.type_system import (  # noqa: E402
    is_generated_always_column,
    parse_case_insensitive_index_expression,
    row_matches_unique_filter,
    unique_key_forces_casefold,
)


def test_snowflake_fetch_unique_keys_hybrid_enforced():
    cur = MagicMock()
    cur.fetchall.return_value = [
        ("SYS_PK", "PRIMARY KEY", "ID", 1, "YES"),
        ("UQ_EMAIL", "UNIQUE", "EMAIL", 1, "YES"),
    ]
    meta = _snowflake_fetch_unique_keys(cur, "PUBLIC", "USERS")
    assert meta["primary_key_columns"] == ["ID"]
    names = {u["name"]: u for u in meta["unique_keys"]}
    assert names["UQ_EMAIL"]["enforced"] is True
    assert names["UQ_EMAIL"]["columns"] == ["EMAIL"]


def test_snowflake_not_enforced_flagged():
    cur = MagicMock()
    cur.fetchall.return_value = [
        ("UQ_EMAIL", "UNIQUE", "EMAIL", 1, "NO"),
    ]
    meta = _snowflake_fetch_unique_keys(cur, "PUBLIC", "USERS")
    assert meta["unique_keys"][0]["enforced"] is False


def test_integrity_skips_snowflake_not_enforced_unique():
    from services.data_integrity import _check_duplicate_keys

    result = _check_duplicate_keys(
        [{"source": "email", "target": "EMAIL"}],
        [{"email": "a"}, {"email": "a"}],
        "strict",
        dest_kind="snowflake",
        primary_key="email",
        sync_mode="append",
        destination_unique_keys=[
            {
                "name": "UQ_EMAIL",
                "columns": ["EMAIL"],
                "enforced": False,
            }
        ],
        target_types={"EMAIL": "VARCHAR"},
    )
    # Advisory UNIQUE must not invent a transfer block.
    assert result["passed"] is True


def test_integrity_blocks_snowflake_enforced_unique():
    from services.data_integrity import _check_duplicate_keys

    result = _check_duplicate_keys(
        [{"source": "email", "target": "EMAIL"}],
        [{"email": "a"}, {"email": "a"}],
        "strict",
        dest_kind="snowflake",
        primary_key="id",
        sync_mode="append",
        destination_unique_keys=[
            {
                "name": "UQ_EMAIL",
                "columns": ["EMAIL"],
                "enforced": True,
            }
        ],
        target_types={"EMAIL": "VARCHAR", "ID": "INTEGER"},
    )
    assert result["passed"] is False


def test_oracle_nlssort_binary_ci_forces_casefold():
    expr = "NLSSORT(\"EMAIL\",'NLS_SORT=BINARY_CI')"
    assert parse_case_insensitive_index_expression(expr) == ["EMAIL"]
    uks = [
        {
            "name": "UQ_EMAIL_CI",
            "columns": [],
            "expression_columns": ["EMAIL"],
            "case_insensitive": True,
        }
    ]
    assert unique_key_forces_casefold("EMAIL", unique_keys=uks) is True


def test_oracle_virtual_identity_generated_tokens():
    assert is_generated_always_column("NUMBER GENERATED ALWAYS") is True
    assert is_generated_always_column("NUMBER GENERATED BY DEFAULT") is False


def test_partial_unique_and_conjunction():
    pred = "([active]=(1) AND [email] IS NOT NULL)"
    assert row_matches_unique_filter({"active": 1, "email": "a@b.c"}, pred)
    assert not row_matches_unique_filter({"active": 0, "email": "a@b.c"}, pred)
    assert not row_matches_unique_filter({"active": 1, "email": None}, pred)
