"""Create-new must recreate the source's key *generator*, or say it did not.

Copying key values is not copying the key: a source ``AUTO_INCREMENT`` /
``IDENTITY`` / ``SERIAL`` column that lands as a plain integer leaves every
checksum matching and the client's first insert after cutover failing. These
tests pin the per-engine decision — carried, relaxed, or refused with a reason
an operator can act on — and that a refusal vetoes MIGRATION PROVEN.
"""

from __future__ import annotations

from services.identity_carry import (
    identity_generation,
    identity_load_mode,
    identity_seed_step,
    plan_identity_carry,
)
from services.migration_certificate import _identity_carry_blockers
from services.schema_fidelity import SourceSchemaCatalog


def _plan(
    *,
    dest: str,
    source_type: str,
    dest_type: str = "BIGINT",
    column: str = "id",
    mapped: bool = True,
    primary_key: list[str] | None = None,
):
    catalog = SourceSchemaCatalog(
        dialect="postgresql",
        columns=[column],
        identity_columns=[column],
        column_types={column: source_type},
    )
    return plan_identity_carry(
        catalog=catalog,
        dest_dialect=dest,
        dest_name_for_source=lambda c: (column if mapped else None),
        dest_type_for_column=lambda _c: dest_type,
        primary_key=[column] if primary_key is None else primary_key,
    )


def test_generation_polarity_read_from_declared_carrier():
    assert identity_generation("BIGINT GENERATED ALWAYS AS IDENTITY") == "always"
    assert identity_generation("BIGINT GENERATED BY DEFAULT AS IDENTITY") == "by_default"
    assert identity_generation("BIGINT AUTO_INCREMENT") == "by_default"
    assert identity_generation("INT IDENTITY(1,1)") == "by_default"
    assert identity_generation("SERIAL") == "by_default"
    assert identity_generation("BIGINT") == ""
    # The catalog's own answer outranks the spelling.
    assert identity_generation("BIGINT", catalog_generation="always") == "always"


def test_postgres_serial_and_identity_carry_as_by_default():
    for source_type in ("SERIAL", "BIGINT GENERATED BY DEFAULT AS IDENTITY"):
        decision = _plan(dest="postgresql", source_type=source_type).decisions[0]
        assert decision.status == "carried", source_type
        assert decision.column_suffix == "GENERATED BY DEFAULT AS IDENTITY"
        assert decision.load_mode == "explicit"
        assert decision.semantics_relaxed is False


def test_generated_always_is_relaxed_and_reported_as_such():
    plan = _plan(dest="postgresql", source_type="BIGINT GENERATED ALWAYS AS IDENTITY")
    decision = plan.decisions[0]
    # The load writes the source's own keys, which ALWAYS refuses outright.
    assert decision.status == "carried"
    assert decision.semantics_relaxed is True
    assert decision.column_suffix == "GENERATED BY DEFAULT AS IDENTITY"
    assert "BY DEFAULT" in decision.reason


def test_mysql_auto_increment_requires_a_key_column():
    carried = _plan(dest="mysql", source_type="BIGINT AUTO_INCREMENT").decisions[0]
    assert carried.status == "carried"
    assert carried.column_suffix == "AUTO_INCREMENT"

    keyless = _plan(
        dest="mysql", source_type="BIGINT AUTO_INCREMENT", primary_key=[]
    ).decisions[0]
    assert keyless.status == "unsupported"
    assert "key column" in keyless.reason


def test_sqlserver_carries_identity_and_demands_identity_insert():
    plan = _plan(dest="sqlserver", source_type="INT IDENTITY(1,1)", dest_type="INT")
    decision = plan.decisions[0]
    assert decision.status == "carried"
    assert decision.column_suffix.upper().startswith("IDENTITY")
    # Explicit source keys need the session to opt in, or row 1 is rejected.
    assert decision.load_mode == "identity_insert"
    assert plan.identity_insert_columns == ["id"]
    assert identity_load_mode("azure_sql") == "identity_insert"
    assert identity_load_mode("postgresql") == "explicit"


def test_oracle_number_key_carries_but_postgres_and_mysql_refuse_it():
    oracle = _plan(
        dest="oracle",
        source_type="NUMBER GENERATED BY DEFAULT AS IDENTITY",
        dest_type="NUMBER(38,0)",
    ).decisions[0]
    assert oracle.status == "carried"
    assert "IDENTITY" in oracle.column_suffix.upper()

    for dest, dest_type in (("postgresql", "NUMERIC(38,0)"), ("mysql", "DECIMAL(38,0)")):
        refused = _plan(
            dest=dest,
            source_type="NUMBER GENERATED BY DEFAULT AS IDENTITY",
            dest_type=dest_type,
        ).decisions[0]
        assert refused.status == "unsupported", dest
        assert refused.column_suffix == ""
        # The operator gets the remedy, not just the refusal.
        assert "BIGINT" in refused.reason


def test_custom_seed_and_increment_are_carried_not_reset_to_one():
    assert identity_seed_step("INT IDENTITY(1000,10)") == (1000, 10)
    assert identity_seed_step(
        "NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 500 INCREMENT BY 5)"
    ) == (500, 5)
    assert identity_seed_step("BIGINT AUTO_INCREMENT") == (1, 1)
    assert identity_seed_step(
        "INT4 GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 10 START WITH 5)"
    ) == (5, 10)
    assert identity_seed_step("INT4 GENERATED BY DEFAULT (INCREMENT BY 10)") == (1, 10)

    sqlserver = _plan(
        dest="sqlserver", source_type="INT IDENTITY(1000,10)", dest_type="INT"
    ).decisions[0]
    assert sqlserver.column_suffix == "IDENTITY(1000,10)"

    for dest in ("postgresql", "oracle"):
        decision = _plan(
            dest=dest, source_type="INT IDENTITY(1000,10)", dest_type="BIGINT"
        ).decisions[0]
        assert decision.column_suffix == (
            "GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 10)"
        ), dest

    # No custom sequence: no needless clause.
    plain = _plan(dest="postgresql", source_type="SERIAL").decisions[0]
    assert plain.column_suffix == "GENERATED BY DEFAULT AS IDENTITY"


def test_fractional_and_text_carriers_are_refused_everywhere():
    for dest_type in ("NUMERIC(12,2)", "TEXT", "VARCHAR(64)", "UUID"):
        decision = _plan(
            dest="postgresql", source_type="SERIAL", dest_type=dest_type
        ).decisions[0]
        assert decision.status == "unsupported", dest_type


def test_unmapped_identity_column_has_nowhere_to_land():
    decision = _plan(dest="postgresql", source_type="SERIAL", mapped=False).decisions[0]
    assert decision.status == "unsupported"
    assert "not mapped" in decision.reason


def test_uncertified_destination_refuses_rather_than_inventing_syntax():
    decision = _plan(dest="snowflake", source_type="SERIAL").decisions[0]
    assert decision.status == "unsupported"
    assert "snowflake" in decision.reason
    assert decision.column_suffix == ""


def test_sqlite_cannot_declare_a_per_column_generator():
    decision = _plan(dest="sqlite", source_type="INTEGER PRIMARY KEY").decisions[0]
    assert decision.status == "unsupported"
    assert "INTEGER PRIMARY KEY" in decision.reason


def test_carrier_that_already_spells_the_generator_is_not_doubled():
    decision = _plan(
        dest="postgresql", source_type="SERIAL", dest_type="BIGSERIAL"
    ).decisions[0]
    assert decision.status == "carried"
    # A second GENERATED clause on a SERIAL column is invalid DDL.
    assert decision.column_suffix == "BIGSERIAL"


def test_non_identity_source_plans_nothing():
    catalog = SourceSchemaCatalog(
        dialect="postgresql", columns=["id"], identity_columns=[]
    )
    plan = plan_identity_carry(
        catalog=catalog,
        dest_dialect="postgresql",
        dest_name_for_source=lambda c: c,
        dest_type_for_column=lambda _c: "BIGINT",
        primary_key=["id"],
    )
    assert plan.decisions == []
    assert plan.column_suffixes == {}


def test_uncarried_generator_vetoes_migration_proven():
    job = {
        "destination_summary": {
            "schema_fidelity": {
                "items": [
                    {
                        "aspect": "identity_sequence",
                        "name": "id",
                        "status": "unsupported",
                        "reason": "Destination type 'DECIMAL(38,0)' cannot hold a generator",
                    }
                ]
            }
        }
    }
    blockers = _identity_carry_blockers(job)
    assert len(blockers) == 1
    assert "'id'" in blockers[0]
    assert "DECIMAL(38,0)" in blockers[0]


def test_carried_or_absent_generator_does_not_block():
    for status in ("carried", "skipped", "not_applicable"):
        job = {
            "destination_summary": {
                "schema_fidelity": {
                    "items": [
                        {"aspect": "identity_sequence", "name": "id", "status": status}
                    ]
                }
            }
        }
        assert _identity_carry_blockers(job) == [], status
    assert _identity_carry_blockers({}) == []
