"""One 100K-row dirty-data population, written in every file format we claim.

Every format in the matrix carries the *same* rows, so a checksum difference
between two cells is a fidelity defect and not a fixture difference. The
population is generated by code (never committed) and is deterministic: row *i*
has the same cells on every host and in every format.

What "dirty" means here, and what each kind of dirt is expected to do:

===================================== =========================================
embedded delimiter / quote / newline  legal RFC-4180 content — must round-trip
UTF-8 / latin-1 / UTF-16 + BOM        must decode, never mojibake
leading-zero identifiers (``0000007``)must stay text, never become ``7``
decimals in scientific notation       must land at full declared scale
several date spellings in one column  must stay text, never be reinterpreted
very long strings (10 KiB)            must not be truncated
nulls as empty / ``NULL`` / ``\\N``    measured per format, never guessed
non-numeric cell in a numeric column  must be **quarantined**, not coerced
ragged rows / duplicate headers       structural — see ``STRUCTURAL_VARIANTS``
blank trailing Excel rows / columns   phantom rows must not become NULL rows
===================================== =========================================

The population is intentionally free of dirt that cannot be expressed in a
typed container (Parquet/Avro/ORC cannot hold a ragged row), so the format grid
compares like with like; structural dirt is proven on the formats that can
carry it, as its own cells.
"""

from __future__ import annotations

import csv
import gzip
import hashlib
import io
import json
import os
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path
from typing import Any, Callable, Iterable, Iterator

DEFAULT_ROWS = int(os.getenv("DATAFLOW_SCALE_ROWS", "100000"))

#: Column order is part of the fixture identity — checksums are positional.
COLUMNS: tuple[str, ...] = (
    "id",
    "acct_code",
    "amount",
    "qty",
    "note",
    "unicode_name",
    "created_at",
    "dob_mixed",
    "flag",
    "null_empty",
    "null_token",
)

#: Declared destination types. ``qty`` is INTEGER on purpose: the fixture puts a
#: non-numeric cell in it so the writer has to quarantine those rows instead of
#: NULLing or truncating them. ``created_at`` carries three different UTC
#: offsets, so a destination that drops the offset lands a different instant and
#: the checksum says so.
DEST_TYPES: dict[str, str] = {
    "id": "BIGINT",
    "acct_code": "VARCHAR(32)",
    "amount": "DECIMAL(18,4)",
    "qty": "INTEGER",
    "note": "TEXT",
    "unicode_name": "VARCHAR(200)",
    "created_at": "TIMESTAMPTZ",
    "dob_mixed": "VARCHAR(32)",
    "flag": "BOOLEAN",
    "null_empty": "VARCHAR(64)",
    "null_token": "VARCHAR(64)",
}


def dest_types(dialect: str = "") -> dict[str, str]:
    """Declared destination types for one dialect.

    MySQL has no timezone-aware carrier — ``DATETIME`` is naive and the engine
    refuses a tz-aware value into it rather than silently dropping the offset
    (correct, and proven as its own cell). The honest MySQL declaration for a
    column of offset-bearing instants is therefore text, which preserves the
    offset instead of losing it.
    """
    types = dict(DEST_TYPES)
    if dialect.lower() in {"mysql", "mariadb"}:
        types["created_at"] = "VARCHAR(40)"
    return types


#: Null spellings are *measured*, not asserted: a delimited file's ``NULL`` text
#: and a JSON string ``"NULL"`` are different claims, and the matrix records
#: what each format actually landed rather than encoding a guess as an
#: expectation. ``null_token`` therefore stays out of the compared projection.
CHECKSUM_COLUMNS: tuple[str, ...] = tuple(c for c in COLUMNS if c != "null_token")

# Row-index modulus for each kind of dirt. Coprime-ish spacing keeps the kinds
# from stacking on the same row, so one failure names one cause.
_DIRT_NOTE = 1000       # embedded delimiter + quote + newline
_DIRT_LONG = 9000       # 10 KiB string
_DIRT_SCI = 7000        # scientific-notation decimal
_DIRT_QUARANTINE = 11000  # non-numeric cell in the INTEGER column
_DIRT_EMPTY = 5000      # empty string (must stay '', never NULL)
_DIRT_TOKEN = 3000      # literal NULL / \N spellings

_LONG_STRING = "L" * 10_000
_EMBEDDED = 'He said "hi", then\nleft; a|b\tc'
_UNICODE_NAMES = ("Ana Muñoz", "北京市データ", "Zoë Ω", "Jose Peña 🌍")
_LATIN1_NAMES = ("Ana Muñoz", "Zoë", "Jose Peña", "Réunion")
_DOB_SPELLINGS = ("2024-01-05", "05/01/2024", "01-05-2024", "5 Jan 2024", "20240105")
_OFFSETS = ("+00:00", "+05:30", "-08:00")

QUARANTINE_VALUE = "N/A"


def is_quarantine_row(i: int) -> bool:
    """True when row *i* carries the non-numeric cell that must be held out."""
    return i % _DIRT_QUARANTINE == 0


def quarantine_row_count(rows: int = DEFAULT_ROWS) -> int:
    return rows // _DIRT_QUARANTINE


def retained_row_count(rows: int = DEFAULT_ROWS) -> int:
    """Rows a quarantining destination must hold after the run."""
    return rows - quarantine_row_count(rows)


def row_text(i: int, *, latin1_safe: bool = False) -> dict[str, str]:
    """Row *i* (1-based) in its text form — what a delimited file carries."""
    names = _LATIN1_NAMES if latin1_safe else _UNICODE_NAMES
    if i % _DIRT_SCI == 0:
        amount = "1.2345E+3"
    else:
        amount = f"{(i % 100000) + 0.1234:.4f}"
    if i % _DIRT_LONG == 0:
        note = _LONG_STRING
    elif i % _DIRT_NOTE == 0:
        note = _EMBEDDED
    else:
        note = f"row {i}"
    qty = QUARANTINE_VALUE if is_quarantine_row(i) else str(i % 500)
    null_empty = "" if i % _DIRT_EMPTY == 0 else "ok"
    if i % _DIRT_TOKEN == 0:
        null_token = "NULL" if (i // _DIRT_TOKEN) % 2 else "\\N"
    else:
        null_token = f"t{i % 97}"
    hour, minute, second = i % 24, i % 60, (i * 7) % 60
    offset = _OFFSETS[i % len(_OFFSETS)]
    return {
        "id": str(i),
        "acct_code": f"{i:07d}",
        "amount": amount,
        "qty": qty,
        "note": note,
        "unicode_name": names[i % len(names)],
        "created_at": (
            f"2024-{(i % 12) + 1:02d}-{(i % 28) + 1:02d}"
            f"T{hour:02d}:{minute:02d}:{second:02d}{offset}"
        ),
        "dob_mixed": _DOB_SPELLINGS[i % len(_DOB_SPELLINGS)],
        "flag": "true" if i % 2 == 0 else "false",
        "null_empty": null_empty,
        "null_token": null_token,
    }


def iter_rows_text(rows: int = DEFAULT_ROWS, *, latin1_safe: bool = False) -> Iterator[dict[str, str]]:
    for i in range(1, rows + 1):
        yield row_text(i, latin1_safe=latin1_safe)


# --------------------------------------------------------------------------- #
# Canonicalization — one function for the expected value and the read-back
# value, so a checksum comparison cannot pass by comparing two different
# renderings of the same cell.
# --------------------------------------------------------------------------- #

_NULL = "<NULL>"


def _canon_amount(value: Any) -> str:
    if value is None:
        return _NULL
    return str(Decimal(str(value)).quantize(Decimal("0.0001")))


def _canon_timestamp(value: Any) -> str:
    if value is None:
        return _NULL
    if isinstance(value, datetime):
        dt = value
    else:
        text = str(value).strip().replace(" ", "T")
        if text.endswith("Z"):
            text = text[:-1] + "+00:00"
        dt = datetime.fromisoformat(text)
    if dt.tzinfo is not None:
        dt = dt.astimezone(timezone.utc).replace(tzinfo=None)
    return dt.isoformat(sep="T", timespec="seconds")


def _canon_bool(value: Any) -> str:
    if value is None:
        return _NULL
    if isinstance(value, bool):
        return "true" if value else "false"
    text = str(value).strip().lower()
    if text in {"true", "t", "1", "yes", "y"}:
        return "true"
    if text in {"false", "f", "0", "no", "n"}:
        return "false"
    return f"<UNPARSED:{text}>"


def _canon_int(value: Any) -> str:
    if value is None:
        return _NULL
    if isinstance(value, str) and not value.strip():
        return _NULL
    return str(int(Decimal(str(value))))


def _canon_text(value: Any) -> str:
    if value is None:
        return _NULL
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


_CANON: dict[str, Callable[[Any], str]] = {
    "id": _canon_int,
    "acct_code": _canon_text,
    "amount": _canon_amount,
    "qty": _canon_int,
    "note": _canon_text,
    "unicode_name": _canon_text,
    "created_at": _canon_timestamp,
    "dob_mixed": _canon_text,
    "flag": _canon_bool,
    "null_empty": _canon_text,
    "null_token": _canon_text,
}


_EMPTY_OR_NULL = "<EMPTY_OR_NULL>"
_ambiguous_empty = False


@contextmanager
def empty_is_ambiguous() -> Iterator[None]:
    """Compare ``''`` and NULL as one value in the ``null_empty`` column.

    RFC 4180 has no NULL: a delimited file writes an empty text cell as nothing,
    so ``''`` and "absent" are the same bytes and no destination can honestly
    recover the difference. Inside this context the compared projection folds the
    two, and the per-cell null tally still records which spelling the destination
    actually holds. Formats that *do* carry the distinction (JSON, Excel,
    Parquet, Avro, ORC, XML) are compared strictly, outside this context.
    """
    global _ambiguous_empty
    previous = _ambiguous_empty
    _ambiguous_empty = True
    try:
        yield
    finally:
        _ambiguous_empty = previous


def canonical_cells(record: dict[str, Any], columns: Iterable[str] = CHECKSUM_COLUMNS) -> tuple[str, ...]:
    """Canonical text for the compared projection of one row."""
    out: list[str] = []
    for col in columns:
        raw = record.get(col)
        if col == "null_empty" and _ambiguous_empty and (raw is None or raw == ""):
            out.append(_EMPTY_OR_NULL)
            continue
        try:
            out.append(_CANON[col](raw))
        except Exception:  # noqa: BLE001 — an unparseable cell is evidence, not a crash
            out.append(f"<UNPARSED:{raw!r}>")
    return tuple(out)


def checksum_rows(
    records: Iterable[dict[str, Any]],
    columns: Iterable[str] = CHECKSUM_COLUMNS,
) -> tuple[str, int]:
    """``(sha256, row_count)`` over the canonical projection, id-ordered.

    Rows are hashed in ``id`` order so a destination that returns them in a
    different physical order still checksums the same — order is not the claim,
    content is.
    """
    cols = tuple(columns)
    keyed: list[tuple[int, tuple[str, ...]]] = []
    for rec in records:
        cells = canonical_cells(rec, cols)
        try:
            key = int(Decimal(str(rec.get("id"))))
        except Exception:  # noqa: BLE001
            key = -1
        keyed.append((key, cells))
    keyed.sort(key=lambda item: item[0])
    digest = hashlib.sha256()
    for _key, cells in keyed:
        digest.update("\x1f".join(cells).encode("utf-8"))
        digest.update(b"\x1e")
    return digest.hexdigest(), len(keyed)


def expected_checksum(
    rows: int = DEFAULT_ROWS,
    *,
    latin1_safe: bool = False,
    include_quarantined: bool = False,
) -> tuple[str, int]:
    """Checksum a correct destination must hold after the run."""
    def _gen() -> Iterator[dict[str, str]]:
        for rec in iter_rows_text(rows, latin1_safe=latin1_safe):
            if include_quarantined or not is_quarantine_row(int(rec["id"])):
                yield rec

    return checksum_rows(_gen())


def null_token_expectation(rows: int = DEFAULT_ROWS) -> dict[str, int]:
    """How many retained rows carry each ``null_token`` spelling."""
    counts = {"NULL": 0, "\\N": 0, "value": 0}
    for i in range(1, rows + 1):
        if is_quarantine_row(i):
            continue
        token = row_text(i)["null_token"]
        if token in counts:
            counts[token] += 1
        else:
            counts["value"] += 1
    return counts


# --------------------------------------------------------------------------- #
# Writers — one population, many containers.
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class FormatSpec:
    """A file format in the matrix: how to write it and how to read it back."""

    name: str          # engine ``format`` for a file source
    suffix: str        # filename suffix
    export_format: str  # engine ``format`` for a file_export destination ('' = none)
    typed: bool = False  # container carries native types (not text)


FORMATS: dict[str, FormatSpec] = {
    "csv": FormatSpec("csv", ".csv", "csv"),
    "tsv": FormatSpec("tsv", ".tsv", "tsv"),
    "psv": FormatSpec("csv", ".psv", "csv"),
    "scsv": FormatSpec("csv", ".csv", "csv"),
    "json": FormatSpec("json", ".json", "json"),
    "jsonl": FormatSpec("jsonl", ".jsonl", "jsonl"),
    "ndjson": FormatSpec("ndjson", ".ndjson", "ndjson"),
    "parquet": FormatSpec("parquet", ".parquet", "parquet", typed=True),
    "avro": FormatSpec("avro", ".avro", "avro", typed=True),
    "orc": FormatSpec("orc", ".orc", "orc", typed=True),
    "excel": FormatSpec("excel", ".xlsx", "excel"),
    "xml": FormatSpec("xml", ".xml", "xml"),
    "csv_gz": FormatSpec("csv", ".csv.gz", ""),
    "fixed_width": FormatSpec("fixed_width", ".txt", ""),
    "yaml": FormatSpec("yaml", ".yaml", ""),
}

_DELIMITERS = {"csv": ",", "tsv": "\t", "psv": "|", "scsv": ";"}

#: Fixed-width layout (column, width) — declared, because a fixed-width file
#: without a declared layout is unparseable by definition.
FIXED_WIDTH_LAYOUT: tuple[tuple[str, int], ...] = (
    ("id", 8),
    ("acct_code", 10),
    ("amount", 16),
    ("qty", 6),
    ("note", 40),
    ("unicode_name", 20),
    ("created_at", 22),
    ("dob_mixed", 12),
    ("flag", 6),
    ("null_empty", 8),
    ("null_token", 8),
)


def _open_text(path: Path, encoding: str, *, compress: bool, bom: bool):
    if compress:
        raw = gzip.open(path, "wb")
    else:
        raw = open(path, "wb")
    if bom:
        raw.write(b"\xef\xbb\xbf" if encoding.startswith("utf-8") else b"")
    stream = io.TextIOWrapper(raw, encoding=encoding, newline="")
    return stream


def write_delimited(
    path: Path,
    rows: int = DEFAULT_ROWS,
    *,
    delimiter: str = ",",
    encoding: str = "utf-8",
    bom: bool = False,
    compress: bool = False,
    latin1_safe: bool = False,
    header: list[str] | None = None,
    variant: str = "",
) -> Path:
    """Write the population as a delimited file.

    ``variant`` injects structural dirt that only a text container can carry:

    ``ragged``      rows with too few and too many fields
    ``dup_header``  the same column name twice
    ``trailing``    blank trailing rows and a blank trailing column
    """
    latin1 = latin1_safe or encoding.lower() in {"latin-1", "latin1", "iso-8859-1"}
    cols = header or list(COLUMNS)
    if variant == "dup_header":
        cols = cols + ["note"]
    if variant == "trailing":
        cols = cols + [""]
    stream = _open_text(path, encoding, compress=compress, bom=bom)
    try:
        writer = csv.writer(stream, delimiter=delimiter, lineterminator="\n")
        writer.writerow(cols)
        for rec in iter_rows_text(rows, latin1_safe=latin1):
            row = [rec[c] for c in COLUMNS]
            if variant == "dup_header":
                row = row + [rec["note"]]
            elif variant == "trailing":
                row = row + [""]
            elif variant == "ragged":
                i = int(rec["id"])
                if i % 25000 == 0:
                    row = row[:6]           # too few fields
                elif i % 25000 == 12500:
                    row = row + ["extra1", "extra2"]  # too many fields
            writer.writerow(row)
        if variant == "trailing":
            for _ in range(5):
                writer.writerow(["" for _ in cols])
    finally:
        stream.close()
    return path


def write_json(path: Path, rows: int = DEFAULT_ROWS) -> Path:
    with open(path, "w", encoding="utf-8") as f:
        f.write("[\n")
        for n, rec in enumerate(iter_rows_text(rows)):
            if n:
                f.write(",\n")
            f.write(json.dumps(rec, ensure_ascii=False))
        f.write("\n]\n")
    return path


def write_jsonl(path: Path, rows: int = DEFAULT_ROWS) -> Path:
    with open(path, "w", encoding="utf-8") as f:
        for rec in iter_rows_text(rows):
            f.write(json.dumps(rec, ensure_ascii=False))
            f.write("\n")
    return path


def write_xml(path: Path, rows: int = DEFAULT_ROWS) -> Path:
    from xml.sax.saxutils import escape

    with open(path, "w", encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n<records>\n')
        for rec in iter_rows_text(rows):
            f.write("  <record>")
            for col in COLUMNS:
                f.write(f"<{col}>{escape(rec[col])}</{col}>")
            f.write("</record>\n")
        f.write("</records>\n")
    return path


def write_yaml(path: Path, rows: int = DEFAULT_ROWS) -> Path:
    """YAML sequence of mappings — quoted scalars, no external dependency."""
    def _q(value: str) -> str:
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'

    with open(path, "w", encoding="utf-8") as f:
        for rec in iter_rows_text(rows):
            f.write("- " + f"{COLUMNS[0]}: {_q(rec[COLUMNS[0]])}\n")
            for col in COLUMNS[1:]:
                f.write(f"  {col}: {_q(rec[col])}\n")
    return path


def write_fixed_width(path: Path, rows: int = DEFAULT_ROWS) -> Path:
    """Padded, delimiter-free records — the layout is ``FIXED_WIDTH_LAYOUT``."""
    with open(path, "w", encoding="utf-8", newline="") as f:
        for rec in iter_rows_text(rows):
            line = "".join(
                str(rec[col]).replace("\n", " ").replace("\t", " ")[:width].ljust(width)
                for col, width in FIXED_WIDTH_LAYOUT
            )
            f.write(line + "\n")
    return path


def _arrow_table(rows: int, *, batch: int = 20000):
    """Arrow batches with native types — decimal stays decimal, ts stays ts."""
    import pyarrow as pa

    schema = pa.schema([
        ("id", pa.int64()),
        ("acct_code", pa.string()),
        ("amount", pa.decimal128(18, 4)),
        # qty is a *string* column on purpose: the fixture's non-numeric cell
        # has to survive the container so the writer is the thing that decides
        # to quarantine it.
        ("qty", pa.string()),
        ("note", pa.string()),
        ("unicode_name", pa.string()),
        ("created_at", pa.timestamp("us", tz="UTC")),
        ("dob_mixed", pa.string()),
        ("flag", pa.bool_()),
        ("null_empty", pa.string()),
        ("null_token", pa.string()),
    ])
    cols: dict[str, list[Any]] = {c: [] for c in COLUMNS}
    for rec in iter_rows_text(rows):
        cols["id"].append(int(rec["id"]))
        cols["acct_code"].append(rec["acct_code"])
        cols["amount"].append(Decimal(rec["amount"]).quantize(Decimal("0.0001")))
        cols["qty"].append(rec["qty"])
        cols["note"].append(rec["note"])
        cols["unicode_name"].append(rec["unicode_name"])
        cols["created_at"].append(datetime.fromisoformat(rec["created_at"]))
        cols["dob_mixed"].append(rec["dob_mixed"])
        cols["flag"].append(rec["flag"] == "true")
        cols["null_empty"].append(rec["null_empty"])
        cols["null_token"].append(rec["null_token"])
        if len(cols["id"]) >= batch:
            yield pa.table({c: cols[c] for c in COLUMNS}, schema=schema)
            cols = {c: [] for c in COLUMNS}
    if cols["id"]:
        yield pa.table({c: cols[c] for c in COLUMNS}, schema=schema)


def write_parquet(path: Path, rows: int = DEFAULT_ROWS) -> Path:
    import pyarrow.parquet as pq

    writer = None
    try:
        for table in _arrow_table(rows):
            if writer is None:
                writer = pq.ParquetWriter(str(path), table.schema)
            writer.write_table(table)
    finally:
        if writer is not None:
            writer.close()
    return path


def write_orc(path: Path, rows: int = DEFAULT_ROWS) -> Path:
    import pyarrow as pa
    import pyarrow.orc as orc

    tables = list(_arrow_table(rows))
    orc.write_table(pa.concat_tables(tables), str(path))
    return path


AVRO_SCHEMA: dict[str, Any] = {
    "type": "record",
    "name": "DirtyRow",
    "fields": [
        {"name": "id", "type": "long"},
        {"name": "acct_code", "type": "string"},
        {
            "name": "amount",
            "type": {"type": "bytes", "logicalType": "decimal", "precision": 18, "scale": 4},
        },
        {"name": "qty", "type": "string"},
        {"name": "note", "type": "string"},
        {"name": "unicode_name", "type": "string"},
        {"name": "created_at", "type": {"type": "long", "logicalType": "timestamp-micros"}},
        {"name": "dob_mixed", "type": "string"},
        {"name": "flag", "type": "boolean"},
        {"name": "null_empty", "type": "string"},
        {"name": "null_token", "type": "string"},
    ],
}


def write_avro(path: Path, rows: int = DEFAULT_ROWS) -> Path:
    import fastavro

    def _records() -> Iterator[dict[str, Any]]:
        for rec in iter_rows_text(rows):
            yield {
                "id": int(rec["id"]),
                "acct_code": rec["acct_code"],
                "amount": Decimal(rec["amount"]).quantize(Decimal("0.0001")),
                "qty": rec["qty"],
                "note": rec["note"],
                "unicode_name": rec["unicode_name"],
                "created_at": datetime.fromisoformat(rec["created_at"]),
                "dob_mixed": rec["dob_mixed"],
                "flag": rec["flag"] == "true",
                "null_empty": rec["null_empty"],
                "null_token": rec["null_token"],
            }

    parsed = fastavro.parse_schema(AVRO_SCHEMA)
    with open(path, "wb") as f:
        fastavro.writer(f, parsed, _records())
    return path


def write_excel(
    path: Path,
    rows: int = DEFAULT_ROWS,
    *,
    variant: str = "",
) -> Path:
    """Write .xlsx with openpyxl's write-only mode.

    ``variant='trailing'`` adds the Excel classic: blank trailing rows and a
    blank trailing column that formatting left behind. Those phantom rows must
    not arrive as NULL rows in the destination.
    """
    from openpyxl import Workbook
    from openpyxl.cell import WriteOnlyCell

    wb = Workbook(write_only=True)
    ws = wb.create_sheet("data")
    header = list(COLUMNS) + ([""] if variant == "trailing" else [])
    ws.append(header)
    for rec in iter_rows_text(rows):
        cells = []
        for col in COLUMNS:
            cell = WriteOnlyCell(ws, value=rec[col])
            # Text format everywhere: Excel would otherwise turn 0000007 into 7
            # and 1.2345E+3 into a float. The fixture's claim is the text.
            cell.number_format = "@"
            cells.append(cell)
        if variant == "trailing":
            cells.append(WriteOnlyCell(ws, value=None))
        ws.append(cells)
    if variant == "trailing":
        for _ in range(5):
            ws.append([None] * len(header))
    wb.save(str(path))
    return path


def write_format(kind: str, path: Path, rows: int = DEFAULT_ROWS) -> Path:
    """Write the population in ``kind`` (a key of ``FORMATS``)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if kind in _DELIMITERS:
        return write_delimited(path, rows, delimiter=_DELIMITERS[kind])
    if kind == "csv_gz":
        return write_delimited(path, rows, compress=True)
    if kind == "json":
        return write_json(path, rows)
    if kind in {"jsonl", "ndjson"}:
        return write_jsonl(path, rows)
    if kind == "xml":
        return write_xml(path, rows)
    if kind == "yaml":
        return write_yaml(path, rows)
    if kind == "fixed_width":
        return write_fixed_width(path, rows)
    if kind == "parquet":
        return write_parquet(path, rows)
    if kind == "orc":
        return write_orc(path, rows)
    if kind == "avro":
        return write_avro(path, rows)
    if kind == "excel":
        return write_excel(path, rows)
    raise ValueError(f"unknown fixture format {kind!r}")


#: Structural / encoding variants, proven on the containers that can carry them.
STRUCTURAL_VARIANTS: dict[str, dict[str, Any]] = {
    "csv_bom": {"format": "csv", "kwargs": {"bom": True}},
    "csv_utf16": {"format": "csv", "kwargs": {"encoding": "utf-16"}},
    "csv_latin1": {"format": "csv", "kwargs": {"encoding": "latin-1", "latin1_safe": True}},
    "csv_ragged": {"format": "csv", "kwargs": {"variant": "ragged"}},
    "csv_dup_header": {"format": "csv", "kwargs": {"variant": "dup_header"}},
    "excel_trailing": {"format": "excel", "kwargs": {"variant": "trailing"}},
}


def write_variant(name: str, path: Path, rows: int = DEFAULT_ROWS) -> Path:
    spec = STRUCTURAL_VARIANTS[name]
    path.parent.mkdir(parents=True, exist_ok=True)
    if spec["format"] == "excel":
        return write_excel(path, rows, **spec["kwargs"])
    return write_delimited(path, rows, **spec["kwargs"])


# --------------------------------------------------------------------------- #
# Independent readers — used to verify a destination *file*, never to write one.
# --------------------------------------------------------------------------- #


def read_delimited(path: Path, *, delimiter: str = ",", encoding: str = "utf-8") -> list[dict[str, Any]]:
    opener = gzip.open if str(path).endswith(".gz") else open
    with opener(path, "rt", encoding=encoding, newline="") as f:  # type: ignore[operator]
        return list(csv.DictReader(f, delimiter=delimiter))


def read_json_file(path: Path) -> list[dict[str, Any]]:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, list) else [data]


def read_jsonl_file(path: Path) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                out.append(json.loads(line))
    return out


def read_arrow(path: Path, *, orc_format: bool = False) -> list[dict[str, Any]]:
    if orc_format:
        import pyarrow.orc as orc

        table = orc.read_table(str(path))
    else:
        import pyarrow.parquet as pq

        table = pq.read_table(str(path))
    return table.to_pylist()


def read_avro_file(path: Path) -> list[dict[str, Any]]:
    import fastavro

    with open(path, "rb") as f:
        return list(fastavro.reader(f))


def _excel_cell_value(cell: Any) -> Any:
    """Recover ``''`` from a typed-but-textless cell.

    xlsx does carry the distinction: an empty text cell is written as a typed
    string cell with no run (``<c t="inlineStr"/>``) while an absent value has no
    ``<c>`` at all. ``openpyxl`` reports both as ``None`` through ``.value``, so
    reading values only would flatten a preserved ``''`` into NULL and accuse the
    writer of a loss that is not in the file.
    """
    value = cell.value
    if value is None and cell.data_type in {"s", "str", "inlineStr"}:
        return ""
    return value


def read_excel_file(path: Path) -> list[dict[str, Any]]:
    from openpyxl import load_workbook

    wb = load_workbook(str(path), read_only=True, data_only=True)
    ws = wb[wb.sheetnames[0]]
    rows = ws.iter_rows()
    header = [str(c.value) if c.value is not None else "" for c in next(rows)]
    out: list[dict[str, Any]] = []
    for row in rows:
        values = [_excel_cell_value(c) for c in row]
        if all(v is None for v in values):
            continue
        out.append({h: v for h, v in zip(header, values) if h})
    wb.close()
    return out


def read_xml_file(path: Path) -> list[dict[str, Any]]:
    from defusedxml.ElementTree import parse

    tree = parse(str(path))
    out: list[dict[str, Any]] = []
    for record in tree.getroot():
        out.append({child.tag: (child.text if child.text is not None else "") for child in record})
    return out


def read_export(path: Path, export_format: str) -> list[dict[str, Any]]:
    """Parse an exported file with a reader that is not the product's writer."""
    fmt = (export_format or "").lower()
    if fmt == "csv":
        return read_delimited(path)
    if fmt == "tsv":
        return read_delimited(path, delimiter="\t")
    if fmt == "json":
        return read_json_file(path)
    if fmt in {"jsonl", "ndjson"}:
        return read_jsonl_file(path)
    if fmt == "parquet":
        return read_arrow(path)
    if fmt == "orc":
        return read_arrow(path, orc_format=True)
    if fmt == "avro":
        return read_avro_file(path)
    if fmt == "excel":
        return read_excel_file(path)
    if fmt == "xml":
        return read_xml_file(path)
    raise ValueError(f"no independent reader for export format {fmt!r}")


def read_bytes_as(export_format: str, payload: bytes, *, suffix: str = "") -> list[dict[str, Any]]:
    """Parse export bytes (object-store payloads) with the same readers."""
    import tempfile

    fmt = (export_format or "").lower()
    with tempfile.NamedTemporaryFile(suffix=suffix or f".{fmt}", delete=False) as tmp:
        tmp.write(payload)
        tmp_path = Path(tmp.name)
    try:
        return read_export(tmp_path, fmt)
    finally:
        os.unlink(tmp_path)


def fixed_width_parse(path: Path) -> list[dict[str, Any]]:
    """Reference parse of the fixed-width fixture, using the declared layout."""
    out: list[dict[str, Any]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            rec: dict[str, Any] = {}
            pos = 0
            for col, width in FIXED_WIDTH_LAYOUT:
                rec[col] = line[pos : pos + width].rstrip()
                pos += width
            out.append(rec)
    return out
