{{ if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataflow.fullname" . }}-api
  labels:
    app.kubernetes.io/component: api
    {{- include "dataflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      {{- include "dataflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        {{- include "dataflow.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "dataflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            {{- include "dataflow.commonEnv" . | nindent 12 }}
            - name: DATAFLOW_WORKER_FLEET
              value: "0"
          {{- include "dataflow.secretEnvFrom" . | nindent 10 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.api.health.livenessPath }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.api.health.readinessPath }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.api.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.api.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.api.affinity | nindent 8 }}
{{- end }}
