{{ if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dataflow.fullname" . }}-api
  labels:
    app.kubernetes.io/component: api
    {{- include "dataflow.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      {{- include "dataflow.selectorLabels" . | nindent 6 }}
{{- end }}
