{{ if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataflow.fullname" . }}-web
  labels:
    app.kubernetes.io/component: web
    {{- include "dataflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      {{- include "dataflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
        {{- include "dataflow.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "dataflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DATAFLOW_API_URL
              value: "https://api.{{ .Values.global.domain }}"
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.web.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.web.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.web.affinity | nindent 8 }}
{{- end }}
