"""Identity / generated-column and external-locator polarity SSOT.

Split out of ``services.type_system`` (a god module over its size budget). These
are *write authority* questions rather than catalog questions: whether the
destination column accepts a client-supplied value at all (GENERATED ALWAYS,
IDENTITY, SERIAL, AUTO_INCREMENT) and whether an external LOB locator (Oracle
BFILE) survives the mapping.

Type-system imports are deferred inside the functions: ``type_system``
re-exports these names, so a module-level import would be circular.
"""

from __future__ import annotations

import re


def is_generated_always_column(inferred: str | None) -> bool:
    """True when destination forbids client-supplied values (GENERATED ALWAYS)."""
    return bool(re.search(r"\bGENERATED\s+ALWAYS\b", (inferred or ""), re.I))


def is_identity_column(inferred: str | None) -> bool:
    """True for SERIAL / IDENTITY / AUTO_INCREMENT carriers."""
    from services.type_system import strip_identity_qualifier

    upper = (inferred or "").upper()
    if not upper:
        return False
    if is_generated_always_column(inferred):
        return True
    if "GENERATED BY DEFAULT" in upper or "AUTO_INCREMENT" in upper:
        return True
    # SQL Server IDENTITY(1,1) — must match before strip_identity_qualifier removes it.
    if re.search(r"\bIDENTITY\b", upper):
        return True
    base = str(strip_identity_qualifier(inferred)).upper()
    return base in {"SERIAL", "BIGSERIAL", "SMALLSERIAL"} or base.startswith("SERIAL")


def generated_always_overwrite_risk(target_type: str) -> bool:
    """Mapping into GENERATED ALWAYS invents overwrite / mid-batch insert failure."""
    return is_generated_always_column(target_type)


def _scalar_carrier_logicals() -> set[str]:
    from services.type_system import (
        LOGICAL_DECIMAL,
        LOGICAL_FLOAT,
        LOGICAL_INTEGER,
        LOGICAL_JSON,
        LOGICAL_STRING,
        LOGICAL_TEXT,
    )

    return {
        LOGICAL_INTEGER,
        LOGICAL_DECIMAL,
        LOGICAL_FLOAT,
        LOGICAL_STRING,
        LOGICAL_TEXT,
        LOGICAL_JSON,
    }


def identity_polarity_would_collapse(source_type: str, target_type: str) -> bool:
    """True when SERIAL/IDENTITY/AUTO_INCREMENT polarity is dropped on the sink.

    Create-new that stamps plain BIGINT while the source was GENERATED ALWAYS
    invents a writable numeric column — Accept risk (or stamp identity DDL).
    """
    from services.type_system import normalize_logical_type

    if not is_identity_column(source_type):
        return False
    if is_identity_column(target_type):
        return False
    return normalize_logical_type(target_type) in _scalar_carrier_logicals()


def identity_domain_would_invent(source_type: str, target_type: str) -> bool:
    """True when plain scalar invents SERIAL/IDENTITY/AUTO_INCREMENT polarity."""
    from services.type_system import normalize_logical_type

    if is_identity_column(source_type):
        return False
    if not is_identity_column(target_type):
        return False
    return normalize_logical_type(source_type) in _scalar_carrier_logicals()


def is_bfile_locator(inferred: str | None) -> bool:
    """True for Oracle BFILE external locator (not inlined LOB bytes)."""
    from services.type_system import strip_identity_qualifier

    upper = str(strip_identity_qualifier(inferred)).upper().strip()
    return upper == "BFILE" or upper.startswith("BFILE(")


def bfile_locator_would_collapse(source_type: str, target_type: str) -> bool:
    """True when BFILE locator polarity would be lost into BLOB/BYTES/text.

    An external file pointer written into inline bytes silently becomes the
    *path text*, not the file — the operator must accept that risk explicitly.
    """
    if not is_bfile_locator(source_type):
        return False
    return not is_bfile_locator(target_type)
