"""Recreate the source's key *generator* on a create-new destination.

Copying key values is not the same as copying the key. A source column declared
``GENERATED BY DEFAULT AS IDENTITY`` / ``AUTO_INCREMENT`` / ``IDENTITY(1,1)``
lands as a plain integer unless the generator is emitted too, and then the
client's first application insert after cutover fails — the row values are
identical, every checksum matches, and the table is still unusable. Row-level
proof cannot see this, because the defect lives in the destination's DDL.

Two failure modes, both real and both silent:

- *generator dropped* — the destination column has no default at all, so
  ``INSERT INTO t (name) VALUES (...)`` raises NOT NULL;
- *generator not advanced* — the column generates, but from 1, so the first
  insert collides with a migrated row. The counter itself is aligned after the
  load by :mod:`services.identity_watermark`; this module only ensures there is
  a generator for it to align.

Fail-closed rules:

- carry only where the destination engine can express the generator *and*
  accept the explicit key values the load is about to write. Everything else is
  reported ``unsupported`` with the engine's reason — never emitted as a plain
  column that looks carried.
- ``GENERATED ALWAYS`` is relaxed to ``BY DEFAULT`` because the load must write
  the source's own key values. That is a semantic change, so it is reported as
  such rather than claimed as a faithful carry.
- a generator and a ``DEFAULT`` on the same column contradict each other; the
  generator wins and the default is reported as dropped.
"""

from __future__ import annotations

import re
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Protocol

import sqlalchemy as sa

if TYPE_CHECKING:  # circular at runtime: schema_fidelity owns the planner
    from services.schema_fidelity import SourceSchemaCatalog

# A catalog row is one identifier per row; the driver decides the container.
CatalogRow = Sequence[object]
# Only identifiers are bound into the catalog queries below.
QueryParams = tuple[str | None, ...]
FetchAll = Callable[[str, QueryParams], Sequence[CatalogRow]]


class DBAPICursor(Protocol):
    """The two calls a PEP 249 cursor needs for a catalog read."""

    def execute(self, operation: str, parameters: QueryParams, /) -> object: ...

    def fetchall(self) -> Sequence[CatalogRow]: ...


class SqlAlchemyConnection(Protocol):
    def execute(
        self, statement: sa.TextClause, parameters: dict[str, str | None], /
    ) -> sa.CursorResult[Any]: ...


__all__ = [
    "IdentityDecision",
    "identity_generation",
    "identity_load_mode",
    "identity_seed_step",
    "plan_identity_carry",
]

# Engines whose generator this module can emit on create-new. Anything absent
# answers "unsupported" with a reason — never a silently plain column.
_SUPPORTED: frozenset[str] = frozenset(
    {"postgresql", "mysql", "mariadb", "sqlserver", "oracle", "sqlite"}
)

# Types that can carry a generator, per destination engine. A source key
# widened to something outside this set (DECIMAL on PostgreSQL, TEXT anywhere)
# cannot hold one, and saying so is the honest answer.
_INTEGER_RE = re.compile(
    r"^(SMALLINT|INT2|INTEGER|INT|INT4|INT8|BIGINT|MEDIUMINT|TINYINT|SERIAL|"
    r"BIGSERIAL|SMALLSERIAL|NUMERIC|DECIMAL|NUMBER)\b",
    re.I,
)
_ZERO_SCALE_RE = re.compile(r"^\s*(?:NUMERIC|DECIMAL|NUMBER)\s*\(\s*\d+\s*(?:,\s*0\s*)?\)?\s*$", re.I)


@dataclass
class IdentityDecision:
    """One source identity column and what the destination can do about it."""

    source_column: str
    dest_column: str
    status: str  # carried | unsupported | unknown
    reason: str
    generation: str = ""  # always | by_default
    column_suffix: str = ""
    load_mode: str = "explicit"  # explicit | identity_insert
    semantics_relaxed: bool = False

    def to_item_kwargs(self) -> dict[str, Any]:
        return {
            "aspect": "identity_sequence",
            "name": self.dest_column or self.source_column,
            "status": self.status,
            "reason": self.reason,
            "source_detail": self.source_column,
            "dest_ddl": self.column_suffix,
        }


@dataclass
class IdentityCarryPlan:
    decisions: list[IdentityDecision] = field(default_factory=list)
    # dest column -> DDL suffix to append after NOT NULL/DEFAULT fragments.
    column_suffixes: dict[str, str] = field(default_factory=dict)
    # Destination columns whose generator refuses a client-supplied value
    # unless the session opts in (SQL Server SET IDENTITY_INSERT).
    identity_insert_columns: list[str] = field(default_factory=list)

    @property
    def carried(self) -> list[IdentityDecision]:
        return [d for d in self.decisions if d.status == "carried"]


def identity_generation(declared_type: str | None, *, catalog_generation: str = "") -> str:
    """``always`` / ``by_default`` / ``""`` from the declared carrier.

    Introspection annotates the logical carrier (``BIGINT AUTO_INCREMENT``,
    ``BIGINT GENERATED ALWAYS AS IDENTITY``) and, where the catalog exposes it,
    passes the generation separately. The explicit catalog value wins.
    """
    gen = (catalog_generation or "").strip().lower()
    if gen in {"always", "by_default"}:
        return gen
    text = (declared_type or "").upper()
    if "GENERATED ALWAYS AS IDENTITY" in text:
        return "always"
    if (
        "GENERATED BY DEFAULT" in text
        or "AUTO_INCREMENT" in text
        or "IDENTITY" in text
        or re.search(r"\b(BIG|SMALL)?SERIAL\b", text)
    ):
        return "by_default"
    return ""


def identity_load_mode(dest_dialect: str) -> str:
    """How the load writes explicit values into a carried generator."""
    return "identity_insert" if _norm(dest_dialect) == "sqlserver" else "explicit"


def _norm(dialect: str | None) -> str:
    d = (dialect or "").strip().lower()
    if d in {"postgres", "postgresql", "redshift"}:
        return "redshift" if d == "redshift" else "postgresql"
    if d in {"mssql", "azure_sql", "azure_sql_database", "sqlserver"}:
        return "sqlserver"
    return d


def _is_integer_carrier(dest_type: str, *, dest: str) -> bool:
    """Can ``dest`` put a generator on a column declared ``dest_type``?

    A key that widened to a fractional carrier cannot generate anywhere. Exact
    zero-scale numerics are integers, but only SQL Server and Oracle accept a
    generator on them — MySQL restricts AUTO_INCREMENT to the integer family
    and PostgreSQL restricts IDENTITY to smallint/integer/bigint.
    """
    base = (dest_type or "").strip()
    if not _INTEGER_RE.match(base):
        return False
    if re.match(r"^\s*(NUMERIC|DECIMAL|NUMBER)\b", base, re.I):
        exact_integer = bool(_ZERO_SCALE_RE.match(base)) or "(" not in base
        return exact_integer and dest in {"sqlserver", "oracle"}
    return True


def _already_generates(dest_type: str) -> bool:
    """True when the invented destination carrier is itself a generator."""
    text = (dest_type or "").upper()
    return bool(
        "AUTO_INCREMENT" in text
        or "IDENTITY" in text
        or re.search(r"\b(BIG|SMALL)?SERIAL\b", text)
    )


# ``INT IDENTITY(5,10)`` / ``... AS IDENTITY (START WITH 5 INCREMENT BY 10)``.
_SEED_STEP_RE = re.compile(
    r"IDENTITY\s*\(\s*(-?\d+)\s*,\s*(-?\d+)\s*\)"
    r"|START\s+WITH\s+(-?\d+)\s+INCREMENT\s+BY\s+(-?\d+)",
    re.I,
)


def identity_seed_step(declared_type: str | None) -> tuple[int, int]:
    """``(seed, increment)`` the source generator runs on; defaults ``(1, 1)``.

    A key sequence declared ``IDENTITY(1000, 10)`` is part of the client's data
    model — recreating it as ``IDENTITY(1,1)`` hands back a table that numbers
    new rows differently from every row already in it.
    """
    match = _SEED_STEP_RE.search(declared_type or "")
    if not match:
        return 1, 1
    seed, step = (match.group(1), match.group(2))
    if seed is None:
        seed, step = (match.group(3), match.group(4))
    return int(seed or 1), int(step or 1)


def _suffix_for(
    dest: str, dest_type: str, *, seed: int = 1, step: int = 1
) -> tuple[str, str]:
    """(ddl_suffix, refusal_reason) for a generator on ``dest``."""
    if dest not in _SUPPORTED:
        return "", (
            f"Key generators are not carried to '{dest}' on create-new: the "
            "engine's generator semantics are not certified here, and emitting "
            "one unproven would be a claim, not a carry."
        )
    if not _is_integer_carrier(dest_type, dest=dest):
        return "", (
            f"Destination type '{dest_type}' cannot hold a generator on "
            f"'{dest}' — the key would widen out of the generator's domain. "
            "Map the key column to an integer type (BIGINT) if its values fit, "
            "and the generator is carried."
        )
    if dest in {"postgresql", "oracle"}:
        clause = "GENERATED BY DEFAULT AS IDENTITY"
        if (seed, step) != (1, 1):
            clause += f" (START WITH {seed} INCREMENT BY {step})"
        return clause, ""
    if dest in {"mysql", "mariadb"}:
        # AUTO_INCREMENT has no per-column step: it follows the server's
        # auto_increment_increment. The seed is set with the high-water repair.
        return "AUTO_INCREMENT", ""
    if dest == "sqlserver":
        return f"IDENTITY({seed},{step})", ""
    if dest == "sqlite":
        # SQLite's only generator is the rowid alias, which the writer emits as
        # part of the PK; see the caller's sqlite branch.
        return "", (
            "SQLite generates keys only through INTEGER PRIMARY KEY rowid "
            "aliasing, which cannot be declared per column here."
        )
    return "", f"No generator syntax known for '{dest}'."


def plan_identity_carry(
    *,
    catalog: SourceSchemaCatalog,
    dest_dialect: str,
    dest_name_for_source: Callable[[str], str | None],
    dest_type_for_column: Callable[[str], str],
    primary_key: list[str] | None = None,
) -> IdentityCarryPlan:
    """Decide, per source identity column, what the destination will carry.

    ``catalog`` is a :class:`services.schema_fidelity.SourceSchemaCatalog`; only
    ``identity_columns``, ``column_types`` and ``dialect`` are read, so the
    preflight planner and the writers can both call this without importing the
    whole fidelity module.
    """
    plan = IdentityCarryPlan()
    dest = _norm(dest_dialect)
    identity_columns = [str(c) for c in catalog.identity_columns]
    if not identity_columns:
        return plan

    column_types = dict(catalog.column_types)
    pk = {str(c) for c in (primary_key or [])}
    for src_col in identity_columns:
        dest_col = dest_name_for_source(src_col)
        generation = identity_generation(column_types.get(src_col))
        if not dest_col:
            plan.decisions.append(
                IdentityDecision(
                    source_column=src_col,
                    dest_column="",
                    status="unsupported",
                    reason=(
                        "Source identity column is not mapped to the destination; "
                        "the generator has nowhere to land."
                    ),
                    generation=generation,
                )
            )
            continue
        dest_type = dest_type_for_column(dest_col)
        if _already_generates(dest_type):
            # The invented carrier already spells the generator (SERIAL, or a
            # declared carrier passed through). Appending a second one would
            # emit invalid DDL.
            plan.decisions.append(
                IdentityDecision(
                    source_column=src_col,
                    dest_column=dest_col,
                    status="carried",
                    reason=(
                        "Destination type already carries the generator; no extra "
                        "clause emitted."
                    ),
                    generation=generation or "by_default",
                    column_suffix=dest_type,
                    load_mode=identity_load_mode(dest),
                )
            )
            continue
        seed, step = identity_seed_step(column_types.get(src_col))
        suffix, refusal = _suffix_for(dest, dest_type, seed=seed, step=step)
        if not suffix:
            plan.decisions.append(
                IdentityDecision(
                    source_column=src_col,
                    dest_column=dest_col,
                    status="unsupported",
                    reason=refusal,
                    generation=generation,
                )
            )
            continue
        if dest in {"mysql", "mariadb"} and dest_col not in pk:
            # MySQL requires the AUTO_INCREMENT column to be a key. Emitting it
            # without one is a create-time error, not a degraded carry.
            plan.decisions.append(
                IdentityDecision(
                    source_column=src_col,
                    dest_column=dest_col,
                    status="unsupported",
                    reason=(
                        "MySQL requires AUTO_INCREMENT to be a key column, and this "
                        "column is not part of the carried PRIMARY KEY."
                    ),
                    generation=generation,
                )
            )
            continue
        relaxed = generation == "always"
        reason = (
            "Key generator emitted on CREATE TABLE; the counter is aligned to the "
            "loaded high-water mark after the write."
        )
        if relaxed:
            reason = (
                "Source is GENERATED ALWAYS; emitted as GENERATED BY DEFAULT so the "
                "load can write the source's own key values. The destination will "
                "generate keys, but will also accept client-supplied ones."
            )
        plan.decisions.append(
            IdentityDecision(
                source_column=src_col,
                dest_column=dest_col,
                status="carried",
                reason=reason,
                generation=generation or "by_default",
                column_suffix=suffix,
                load_mode=identity_load_mode(dest),
                semantics_relaxed=relaxed,
            )
        )
        plan.column_suffixes[dest_col] = suffix
        if identity_load_mode(dest) == "identity_insert":
            plan.identity_insert_columns.append(dest_col)
    return plan


# --------------------------------------------------------------------------
# Destination verification
# --------------------------------------------------------------------------
# Emitting a generator clause is a claim. Engines silently ignore some of them
# (SQLAlchemy drops ``autoincrement`` on a MySQL DECIMAL key, Oracle takes an
# IDENTITY only on a NUMBER carrier), so the certificate may only say "carried"
# after the destination's own catalog reports the generator.
_GENERATOR_QUERY: dict[str, str] = {
    "postgresql": (
        "SELECT a.attname FROM pg_attribute a "
        "JOIN pg_class c ON c.oid = a.attrelid "
        "JOIN pg_namespace n ON n.oid = c.relnamespace "
        "LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum "
        "WHERE c.relname = ? AND n.nspname = COALESCE(?, 'public') "
        "AND a.attnum > 0 AND ("
        "a.attidentity <> '' "
        "OR position('nextval' in COALESCE(pg_get_expr(d.adbin, d.adrelid), '')) > 0)"
    ),
    "mysql": (
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name = ? AND table_schema = COALESCE(?, DATABASE()) "
        "AND LOCATE('auto_increment', LOWER(extra)) > 0"
    ),
    "sqlserver": (
        "SELECT c.name FROM sys.identity_columns c "
        "JOIN sys.tables t ON t.object_id = c.object_id "
        "JOIN sys.schemas s ON s.schema_id = t.schema_id "
        "WHERE t.name = ? AND s.name = COALESCE(?, SCHEMA_NAME())"
    ),
    "oracle": (
        "SELECT column_name FROM all_tab_identity_cols "
        "WHERE table_name = ? AND owner = COALESCE(?, SYS_CONTEXT('USERENV', "
        "'CURRENT_SCHEMA'))"
    ),
}
_GENERATOR_QUERY["mariadb"] = _GENERATOR_QUERY["mysql"]


def destination_generator_columns(
    *,
    dialect: str,
    schema: str,
    table: str,
    fetchall: FetchAll,
) -> set[str] | None:
    """Columns the destination itself reports as generators, or ``None``.

    ``None`` means the catalog could not be read — which the caller must keep as
    *unknown*, never as proof the generator is absent.
    """
    dest = _norm(dialect)
    query = _GENERATOR_QUERY.get(dest)
    if not query:
        return None
    unquoted = str(table).strip().strip('"').strip("`").strip("[").strip("]")
    if dest == "oracle":
        unquoted = unquoted if unquoted != unquoted.lower() else unquoted.upper()
        schema_arg = (schema or "").upper() or None
    else:
        schema_arg = schema or None
    try:
        rows = fetchall(query, (unquoted, schema_arg))
    except Exception:  # noqa: BLE001 — an unreadable catalog is "unknown"
        return None
    return {str(r[0]) for r in (rows or [])}


def dbapi_percent_fetchall(cursor: DBAPICursor) -> FetchAll:
    """Adapt a DB-API cursor (``%s`` paramstyle: psycopg2, pymysql) to the catalog reader."""

    def _run(sql: str, params: QueryParams) -> Sequence[CatalogRow]:
        cursor.execute(sql.replace("?", "%s"), params)
        return cursor.fetchall()

    return _run


psycopg2_fetchall = dbapi_percent_fetchall


def sqlalchemy_fetchall(conn: SqlAlchemyConnection) -> FetchAll:
    """Adapt a SQLAlchemy connection to the catalog reader."""

    def _run(sql: str, params: QueryParams) -> Sequence[CatalogRow]:
        bound = sql
        named: dict[str, str | None] = {}
        for idx, value in enumerate(params):
            bound = bound.replace("?", f":p{idx}", 1)
            named[f"p{idx}"] = value
        return conn.execute(sa.text(bound), named).fetchall()

    return _run
