#!/usr/bin/env python3
"""Append roadmap connectors until catalog reaches target size."""
import json
from pathlib import Path

CATALOG = Path(__file__).resolve().parents[1] / "apps/api/data/connector_catalog.json"
TARGET = 650

EXTRAS = [
    ("apache_iceberg", "Apache Iceberg", "lake", "planned", "Open table format for data lakes"),
    ("delta_lake", "Delta Lake", "lake", "planned", "ACID transactions on data lakes"),
    ("apache_hudi", "Apache Hudi", "lake", "planned", "Incremental processing on data lakes"),
    ("apache_druid", "Apache Druid", "warehouse", "planned", "Real-time analytics database"),
    ("clickhouse", "ClickHouse", "warehouse", "planned", "Column-oriented OLAP database"),
    ("apache_pinot", "Apache Pinot", "warehouse", "planned", "Real-time distributed OLAP"),
    ("cockroachdb", "CockroachDB", "database", "planned", "Distributed SQL database"),
    ("cassandra", "Apache Cassandra", "database", "planned", "Wide-column NoSQL store"),
    ("couchbase", "Couchbase", "database", "planned", "Document and key-value database"),
    ("neo4j", "Neo4j", "database", "planned", "Graph database platform"),
    ("influxdb", "InfluxDB", "database", "planned", "Time-series database"),
    ("timescaledb", "TimescaleDB", "database", "planned", "Time-series on PostgreSQL"),
    ("singlestore", "SingleStore", "database", "planned", "Distributed SQL database"),
    ("firebolt", "Firebolt", "warehouse", "planned", "Cloud data warehouse"),
    ("motherduck", "MotherDuck", "warehouse", "planned", "DuckDB in the cloud"),
    ("duckdb", "DuckDB", "database", "planned", "In-process analytical database"),
    ("dremio", "Dremio", "warehouse", "planned", "Data lakehouse engine"),
    ("starburst", "Starburst", "warehouse", "planned", "Trino-based query engine"),
    ("presto", "Presto", "warehouse", "planned", "Distributed SQL query engine"),
    ("trino", "Trino", "warehouse", "planned", "Fast distributed SQL engine"),
    ("dbt_cloud", "dbt Cloud", "saas", "planned", "Analytics engineering platform"),
    ("fivetran", "Fivetran", "saas", "planned", "ELT connector marketplace reference"),
    ("segment", "Segment", "saas", "planned", "Customer data platform"),
    ("mixpanel", "Mixpanel", "saas", "planned", "Product analytics export"),
    ("amplitude", "Amplitude", "saas", "planned", "Product analytics warehouse sync"),
    ("zendesk", "Zendesk", "saas", "planned", "Support ticket and user sync"),
    ("jira", "Jira", "saas", "planned", "Issue and project data export"),
    ("github", "GitHub", "saas", "planned", "Repository and issue metadata"),
    ("gitlab", "GitLab", "saas", "planned", "DevOps platform data export"),
    ("notion", "Notion", "saas", "planned", "Workspace database export"),
    ("airtable", "Airtable", "saas", "planned", "Spreadsheet-database hybrid"),
    ("google_sheets", "Google Sheets", "saas", "planned", "Spreadsheet source and destination"),
    ("avro", "Avro", "file", "planned", "Row-based binary serialization format"),
    ("orc", "ORC", "file", "planned", "Columnar file format for Hive"),
    ("xml", "XML", "file", "planned", "Structured XML document parsing"),
    ("yaml", "YAML", "file", "planned", "Configuration and data files"),
    ("fixed_width", "Fixed width", "file", "planned", "Mainframe-style fixed column files"),
    ("protobuf", "Protocol Buffers", "file", "planned", "Binary structured data format"),
    ("apache_kafka", "Apache Kafka", "streaming", "planned", "Distributed event streaming"),
    ("amazon_kinesis", "Amazon Kinesis", "streaming", "planned", "AWS real-time data streaming"),
    ("google_pubsub", "Google Pub/Sub", "streaming", "planned", "GCP messaging service"),
    ("azure_event_hubs", "Azure Event Hubs", "streaming", "planned", "Azure streaming ingestion"),
    ("rabbitmq", "RabbitMQ", "streaming", "planned", "Message broker integration"),
    ("apache_pulsar", "Apache Pulsar", "streaming", "planned", "Cloud-native messaging"),
    ("azure_synapse", "Azure Synapse", "warehouse", "planned", "Microsoft analytics service"),
    ("azure_sql", "Azure SQL", "database", "planned", "Managed SQL Server on Azure"),
    ("azure_cosmos_db", "Azure Cosmos DB", "database", "planned", "Multi-model Azure database"),
    ("ibm_db2_warehouse", "IBM Db2 Warehouse", "warehouse", "planned", "IBM analytics warehouse"),
    ("teradata_vantage", "Teradata Vantage", "warehouse", "planned", "Enterprise analytics platform"),
    ("sap_hana", "SAP HANA", "database", "planned", "In-memory enterprise database"),
    ("salesforce_commerce", "Salesforce Commerce", "saas", "planned", "B2C commerce cloud data"),
    ("shopify_plus", "Shopify Plus", "saas", "planned", "Enterprise commerce exports"),
    ("workday", "Workday", "saas", "planned", "HR and finance cloud data"),
    ("netsuite", "NetSuite", "saas", "planned", "ERP and financial data"),
    ("servicenow", "ServiceNow", "saas", "planned", "IT service management data"),
    ("greenplum", "Greenplum", "warehouse", "planned", "MPP analytics database"),
    ("vertica", "Vertica", "warehouse", "planned", "Columnar analytics platform"),
    ("exasol", "Exasol", "warehouse", "planned", "In-memory analytics database"),
    ("yellowbrick", "Yellowbrick", "warehouse", "planned", "Elastic data warehouse"),
    ("apache_kylin", "Apache Kylin", "warehouse", "planned", "OLAP engine for big data"),
    ("apache_spark", "Apache Spark", "lake", "planned", "Unified analytics engine"),
    ("minio", "MinIO", "lake", "planned", "S3-compatible object storage"),
    ("wasabi", "Wasabi", "lake", "planned", "Hot cloud object storage"),
    ("backblaze_b2", "Backblaze B2", "lake", "planned", "S3-compatible cloud storage"),
    ("oracle_autonomous", "Oracle Autonomous DB", "database", "planned", "Self-driving Oracle database"),
    ("mariadb", "MariaDB", "database", "planned", "Open-source relational database"),
    ("percona_mysql", "Percona MySQL", "database", "planned", "Enterprise MySQL distribution"),
    ("planetscale", "PlanetScale", "database", "planned", "Serverless MySQL platform"),
    ("supabase", "Supabase", "database", "planned", "Postgres development platform"),
    ("neon", "Neon", "database", "planned", "Serverless Postgres"),
    ("fauna", "Fauna", "database", "planned", "Document-relational database"),
    ("couchdb", "Apache CouchDB", "database", "planned", "Document-oriented NoSQL"),
    ("ravendb", "RavenDB", "database", "planned", "Document database for .NET"),
    ("marklogic", "MarkLogic", "database", "planned", "Multi-model enterprise database"),
    ("intercom", "Intercom", "saas", "planned", "Customer messaging platform"),
    ("braze", "Braze", "saas", "planned", "Customer engagement platform"),
    ("klaviyo", "Klaviyo", "saas", "planned", "Marketing automation data"),
    ("mailchimp", "Mailchimp", "saas", "planned", "Email marketing exports"),
    ("twilio", "Twilio", "saas", "planned", "Communications API data"),
    ("stripe_billing", "Stripe Billing", "saas", "planned", "Subscription billing exports"),
    ("chargebee", "Chargebee", "saas", "planned", "Subscription management"),
    ("quickbooks", "QuickBooks", "saas", "planned", "Accounting and finance data"),
    ("xero", "Xero", "saas", "planned", "Cloud accounting platform"),
    ("sage", "Sage", "saas", "planned", "ERP and accounting exports"),
    ("marketo", "Marketo", "saas", "planned", "Marketing automation platform"),
    ("pardot", "Pardot", "saas", "planned", "B2B marketing automation"),
    ("eloqua", "Oracle Eloqua", "saas", "planned", "B2B marketing platform"),
    ("dynamics_365", "Dynamics 365", "saas", "planned", "Microsoft business applications"),
    ("power_bi", "Power BI", "saas", "planned", "Business intelligence datasets"),
    ("tableau", "Tableau", "saas", "planned", "Analytics and visualization exports"),
    ("looker", "Looker", "saas", "planned", "BI semantic layer exports"),
    ("mode", "Mode", "saas", "planned", "Analytics workspace data"),
    ("sigma", "Sigma Computing", "saas", "planned", "Spreadsheet BI on warehouses"),
    ("hex", "Hex", "saas", "planned", "Collaborative analytics notebooks"),
    ("jsonl", "JSON Lines", "file", "planned", "Newline-delimited JSON records"),
    ("ndjson", "NDJSON", "file", "planned", "Streaming JSON document format"),
    ("feather", "Feather", "file", "planned", "Columnar in-memory format"),
    ("arrow_ipc", "Apache Arrow IPC", "file", "planned", "Columnar interchange format"),
    ("hdf5", "HDF5", "file", "planned", "Hierarchical scientific data format"),
    ("geojson", "GeoJSON", "file", "planned", "Geographic feature encoding"),
    ("shapefile", "Shapefile", "file", "planned", "GIS vector data format"),
    ("kml", "KML", "file", "planned", "Geographic markup language"),
    ("edi_x12", "EDI X12", "file", "planned", "Electronic data interchange"),
    ("swift_mt", "SWIFT MT", "file", "planned", "Financial messaging format"),
    ("hl7", "HL7", "file", "planned", "Healthcare data interchange"),
    ("fhir", "FHIR", "file", "planned", "Healthcare resources JSON/XML"),
    ("logfmt", "Logfmt", "file", "planned", "Key-value log line format"),
    ("cef", "CEF", "file", "planned", "Common event format logs"),
    ("syslog", "Syslog", "file", "planned", "System log message streams"),
    ("confluent_cloud", "Confluent Cloud", "streaming", "planned", "Managed Kafka service"),
    ("redpanda", "Redpanda", "streaming", "planned", "Kafka-compatible streaming"),
    ("aws_msk", "Amazon MSK", "streaming", "planned", "Managed Kafka on AWS"),
    ("azure_service_bus", "Azure Service Bus", "streaming", "planned", "Enterprise messaging"),
    ("nats", "NATS", "streaming", "planned", "Cloud-native messaging system"),
    ("mqtt", "MQTT", "streaming", "planned", "IoT pub/sub protocol"),
    ("apache_flume", "Apache Flume", "streaming", "planned", "Log aggregation pipeline"),
    ("apache_beam", "Apache Beam", "streaming", "planned", "Unified batch and streaming"),
    ("google_dataflow", "Google Dataflow", "streaming", "planned", "Managed Beam pipelines"),
    ("aws_glue", "AWS Glue", "lake", "planned", "Serverless ETL catalog"),
    ("azure_data_factory", "Azure Data Factory", "lake", "planned", "Cloud ETL orchestration"),
    ("informatica", "Informatica", "saas", "planned", "Enterprise iPaaS reference"),
    ("talend", "Talend", "saas", "planned", "Data integration platform"),
    ("matillion", "Matillion", "saas", "planned", "Cloud ELT for warehouses"),
    ("stitch", "Stitch", "saas", "planned", "ELT data pipeline service"),
    ("airbyte", "Airbyte", "saas", "planned", "Open-source ELT reference"),
    ("hevo", "Hevo", "saas", "planned", "No-code data pipeline platform"),
    ("rivery", "Rivery", "saas", "planned", "SaaS ELT automation"),
    ("portable", "Portable", "saas", "planned", "Long-tail SaaS connectors"),
    ("hightouch", "Hightouch", "saas", "planned", "Reverse ETL platform"),
    ("census", "Census", "saas", "planned", "Reverse ETL to warehouses"),
    ("rudderstack", "RudderStack", "saas", "planned", "Customer data infrastructure"),
    ("mparticle", "mParticle", "saas", "planned", "Customer data platform"),
    ("tealium", "Tealium", "saas", "planned", "Customer data orchestration"),
    ("lytics", "Lytics", "saas", "planned", "Customer data platform"),
    ("treasure_data", "Treasure Data", "warehouse", "planned", "Customer data platform warehouse"),
    ("splunk", "Splunk", "saas", "planned", "Observability and log analytics"),
    ("datadog", "Datadog", "saas", "planned", "Monitoring and metrics export"),
    ("new_relic", "New Relic", "saas", "planned", "Observability platform data"),
    ("pagerduty", "PagerDuty", "saas", "planned", "Incident management exports"),
    ("opsgenie", "Opsgenie", "saas", "planned", "Alerting and on-call data"),
    ("launchdarkly", "LaunchDarkly", "saas", "planned", "Feature flag analytics"),
    ("optimizely", "Optimizely", "saas", "planned", "Experimentation platform"),
    ("fullstory", "FullStory", "saas", "planned", "Digital experience analytics"),
    ("heap", "Heap", "saas", "planned", "Product analytics autocapture"),
    ("pendo", "Pendo", "saas", "planned", "Product experience analytics"),
    ("gainsight", "Gainsight", "saas", "planned", "Customer success platform"),
    ("totango", "Totango", "saas", "planned", "Customer success analytics"),
    ("churnzero", "ChurnZero", "saas", "planned", "Customer success data"),
    ("vitally", "Vitally", "saas", "planned", "B2B customer success hub"),
    ("gong", "Gong", "saas", "planned", "Revenue intelligence conversations"),
    ("outreach", "Outreach", "saas", "planned", "Sales engagement platform"),
    ("salesloft", "Salesloft", "saas", "planned", "Sales engagement exports"),
    ("apollo", "Apollo.io", "saas", "planned", "Sales intelligence data"),
    ("zoominfo", "ZoomInfo", "saas", "planned", "B2B contact database"),
    ("clearbit", "Clearbit", "saas", "planned", "B2B enrichment data"),
    ("leadiq", "LeadIQ", "saas", "planned", "Prospecting contact data"),
    ("linkedin_ads", "LinkedIn Ads", "saas", "planned", "Advertising campaign exports"),
    ("google_ads", "Google Ads", "saas", "planned", "Advertising performance data"),
    ("facebook_ads", "Meta Ads", "saas", "planned", "Social advertising exports"),
    ("tiktok_ads", "TikTok Ads", "saas", "planned", "Short-form ads analytics"),
    ("pinterest_ads", "Pinterest Ads", "saas", "planned", "Visual ads campaign data"),
    ("snapchat_ads", "Snapchat Ads", "saas", "planned", "Mobile ads exports"),
    ("twitter_ads", "X Ads", "saas", "planned", "Social ads performance"),
    ("reddit_ads", "Reddit Ads", "saas", "planned", "Community ads analytics"),
    ("bing_ads", "Microsoft Ads", "saas", "planned", "Search advertising exports"),
    ("criteo", "Criteo", "saas", "planned", "Commerce media platform"),
    ("the_trade_desk", "The Trade Desk", "saas", "planned", "Programmatic advertising"),
    ("appsflyer", "AppsFlyer", "saas", "planned", "Mobile attribution analytics"),
    ("adjust", "Adjust", "saas", "planned", "Mobile measurement partner"),
    ("branch", "Branch", "saas", "planned", "Mobile linking and attribution"),
    ("singular", "Singular", "saas", "planned", "Marketing analytics platform"),
    ("kochava", "Kochava", "saas", "planned", "Mobile attribution data"),
    ("firebase", "Firebase", "saas", "planned", "Google app analytics exports"),
    ("app_store_connect", "App Store Connect", "saas", "planned", "iOS app metrics"),
    ("google_play_console", "Google Play Console", "saas", "planned", "Android app metrics"),
]


def main() -> None:
    with CATALOG.open(encoding="utf-8") as f:
        data = json.load(f)
    connectors = data["connectors"]
    ids = {c["id"] for c in connectors}
    added = 0
    for eid, name, category, status, description in EXTRAS:
        if eid in ids:
            continue
        connectors.append(
            {
                "id": eid,
                "name": name,
                "category": category,
                "status": status,
                "description": description,
            }
        )
        ids.add(eid)
        added += 1
    data["connectors"] = connectors
    data["total"] = len(connectors)
    with CATALOG.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=1)
        f.write("\n")
    print(f"added={added} total={len(connectors)} target={TARGET}")


if __name__ == "__main__":
    main()
