#!/usr/bin/env python3
"""Generate apps/web/src/lib/genericSqlMap.ts from generic_sql.py mappings."""
import json
import pathlib
import sys

# Ensure apps/api is on the path so generic_sql.py can be imported.
REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "apps/api"))

from connectors import generic_sql as gs


def main() -> None:
    info = {}
    for cid, drivername in gs._DRIVERNAME_MAP.items():
        port = gs._DEFAULT_PORT_MAP.get(cid, 0)
        info[cid] = {"base": drivername, "port": port}

    # First-class SQL engines also need placeholder/defaults lookup.
    extras = {
        "postgresql": {"base": "postgresql+psycopg2", "port": 5432},
        "mysql": {"base": "mysql+pymysql", "port": 3306},
        "redshift": {"base": "postgresql+psycopg2", "port": 5439},
    }
    for k, v in extras.items():
        info.setdefault(k, v)

    # Backfill default ports for Spark variants from the explicit sparksql entry.
    if "spark" in info and info["spark"]["port"] == 0 and "sparksql" in info:
        info["spark"]["port"] = info["sparksql"]["port"]
    if "apache_spark" in info and info["apache_spark"]["port"] == 0 and "sparksql" in info:
        info["apache_spark"]["port"] = info["sparksql"]["port"]

    out_path = REPO / "apps/web/src/lib/genericSqlMap.ts"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Generated by scripts/generate_generic_sql_map.py from apps/api/connectors/generic_sql.py",
        "// Do not edit manually; re-run the script to update.",
        "",
        "export interface GenericSqlInfo {",
        "  base: string;",
        "  port: number;",
        "}",
        "",
        f"export const GENERIC_SQL_INFO: Record<string, GenericSqlInfo> = {json.dumps(info, indent=2, sort_keys=True)};",
        "",
    ]
    out_path.write_text("\n".join(lines))
    print(f"{out_path} written with {len(info)} generic SQL entries")


if __name__ == "__main__":
    main()
