"""Live post-load structural attestation: did the destination get the *objects*?

A row-perfect load can still hand the client an unusable table — no primary key,
a dropped unique constraint, a missing foreign key, an index the application
plans against, a NOT NULL that became nullable, a lost default, or an identity
counter still pointing at 1 so the first application insert collides with a
migrated row. None of that is visible to a checksum: the defect lives in the
destination's catalog, not in its data.

``services.physical_state_diff`` and ``services.identity_watermark`` read it back
after the write, on their own connections. Their unit coverage is SQLite; this
harness drives the product path (``execute_tracked``) with real PostgreSQL and
MySQL destinations and records, per aspect, what the attestation actually said.

Each scenario declares the verdict it expects. A measurement that disagrees is
reported as a gap — nothing here is asserted into green, and an aspect the
engine cannot answer must come back ``unreadable`` rather than carried.
"""

from __future__ import annotations

import json
import sys
from typing import Any

sys.path.insert(0, "/home/ubuntu/repos/DataFlow/apps/api")
sys.path.insert(0, "/home/ubuntu/repos/DataFlow/apps/api/scripts")

from live_migration_scenario_matrix import (  # noqa: E402
    DST,
    SRC,
    dest_count,
    dest_exec,
    dest_table_ref,
    m,
    pg_exec,
    run_transfer,
)

ENGINES = ["postgresql", "mysql"]

# Aspects ``verify_physical_state`` reports. Kept explicit so a renamed or
# silently dropped aspect shows up as missing evidence instead of vanishing.
ASPECTS = (
    "primary_key",
    "unique_constraints",
    "foreign_keys",
    "indexes",
    "not_null",
    "defaults",
    "check_constraints",
)

PARENT = "attest_parent"


def _mappings() -> list[dict[str, Any]]:
    return [
        m("id", "id", "BIGINT", "BIGINT"),
        m("email", "email", "VARCHAR(64)", "VARCHAR(64)"),
        m("parent_id", "parent_id", "BIGINT", "BIGINT"),
        m("status", "status", "VARCHAR(16)", "VARCHAR(16)"),
    ]


def _seed_source() -> None:
    """A source table carrying every structural guarantee at once."""
    pg_exec(
        [
            # A carried FK on a PostgreSQL destination references the same parent
            # table, so the parent cannot be dropped while that destination still
            # exists. Drop the destination first rather than cascading — CASCADE
            # would delete the very object the previous run's attestation proved.
            f"DROP TABLE IF EXISTS {DST}",
            f"DROP TABLE IF EXISTS {SRC}",
            f"DROP TABLE IF EXISTS {PARENT}",
            f"CREATE TABLE {PARENT} (id BIGINT PRIMARY KEY)",
            "INSERT INTO %s VALUES (1), (2), (3)" % PARENT,
            f"""CREATE TABLE {SRC} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email VARCHAR(64) NOT NULL UNIQUE,
                    parent_id BIGINT REFERENCES {PARENT}(id),
                    status VARCHAR(16) NOT NULL DEFAULT 'active',
                    CONSTRAINT {SRC}_status_ck CHECK (status <> '')
                )""",
            f"CREATE INDEX {SRC}_status_idx ON {SRC} (status)",
        ]
    )
    pg_exec(
        [
            f"INSERT INTO {SRC} (id, email, parent_id, status) "
            f"VALUES ({i}, 'u{i}@example.com', {(i % 3) + 1}, 'active')"
            for i in range(1, 21)
        ]
    )
    # Advance the source generator past the explicit values the load writes, the
    # way a real source sits after years of application inserts.
    pg_exec([f"SELECT setval(pg_get_serial_sequence('{SRC}', 'id'), 20, true)"])


def _drop_dest(engine: str) -> None:
    ref = dest_table_ref(engine)
    dest_exec(engine, [f"DROP TABLE {ref}"])


def _dest_parent(engine: str) -> None:
    """The parent table a carried foreign key needs on the destination side."""
    if engine == "postgresql":
        return  # same database as the source; the parent is already seeded there
    dest_exec(
        engine,
        [
            f"DROP TABLE {PARENT}",
            f"CREATE TABLE {PARENT} (id BIGINT PRIMARY KEY)",
            f"INSERT INTO {PARENT} (id) VALUES (1), (2), (3)",
        ],
    )


def _create_dest_bare(engine: str) -> None:
    """A destination an operator pre-created *without* the guarantees.

    This is the common real shape: someone ran a hand-written CREATE TABLE from a
    column list. Rows will land and every checksum will match; the attestation is
    the only thing that can tell the operator the table is not the source's table.
    """
    ref = dest_table_ref(engine)
    dest_exec(
        engine,
        [
            f"DROP TABLE {ref}",
            f"CREATE TABLE {ref} ("
            "id BIGINT, email VARCHAR(64), parent_id BIGINT, status VARCHAR(16))",
        ],
    )


def _aspect_verdicts(recon: dict[str, Any]) -> dict[str, Any]:
    state = (recon.get("physical_state") or {}) if isinstance(recon, dict) else {}
    objects = state.get("schema_objects") or {}
    findings = objects.get("aspects") or objects.get("findings") or {}
    out: dict[str, Any] = {}
    for aspect in ASPECTS:
        entry = findings.get(aspect)
        if isinstance(entry, dict):
            out[aspect] = str(entry.get("status") or entry.get("verdict") or "unknown")
        elif isinstance(entry, str):
            out[aspect] = entry
        else:
            out[aspect] = "no_evidence"
    out["_verified"] = objects.get("verified")
    out["_identity"] = state.get("identity_watermark") or {"no_evidence": True}
    return out


def scenario_create_new(engine: str) -> dict[str, Any]:
    """Create-new destination: the planner carries the objects it can."""
    _drop_dest(engine)
    _seed_source()
    _dest_parent(engine)
    res = run_transfer(engine, _mappings(), sync_mode="full_refresh_append")
    return {
        "scenario": "create-new destination",
        "engine": engine,
        "rows": dest_count(engine),
        "run_success": res["success"],
        "error": res["error"],
        "aspects": _aspect_verdicts(res.get("reconciliation") or {}),
        "expected_aspects": dict.fromkeys(ASPECTS, "carried"),
        "expected_identity_verified": True,
        "expected": "every aspect carried by the create, identity generator "
        "present and its counter advanced past the 20 migrated rows",
    }


def scenario_bare_existing(engine: str) -> dict[str, Any]:
    """Pre-created destination missing every guarantee: must be reported absent."""
    _drop_dest(engine)
    _seed_source()
    _dest_parent(engine)
    _create_dest_bare(engine)
    res = run_transfer(engine, _mappings(), sync_mode="full_refresh_append")
    return {
        "scenario": "operator-created destination without guarantees",
        "engine": engine,
        "rows": dest_count(engine),
        "run_success": res["success"],
        "error": res["error"],
        "aspects": _aspect_verdicts(res.get("reconciliation") or {}),
        # Foreign keys are the one aspect the engine still carries here: they are
        # added after the load by ``services.foreign_key_carry``, which an
        # existing table accepts. Everything a CREATE would have carried is
        # missing from a hand-written table and has to be reported absent.
        "expected_aspects": {
            **dict.fromkeys(ASPECTS, "absent"),
            "foreign_keys": "carried",
        },
        "expected_identity_verified": False,
        "expected": "everything a CREATE would have carried reported absent — "
        "never carried, never silently green; foreign_keys carried by the "
        "post-load ALTER; identity generator unverified",
    }


def _gaps(result: dict[str, Any]) -> list[str]:
    """Where the measurement disagrees with the verdict the scenario declared.

    Printing an expectation as prose lets a regression pass review unnoticed, so
    the comparison is mechanical: an aspect that came back anything other than
    its declared verdict is a gap, and so is an identity claim in either
    direction.
    """
    if result.get("harness_error"):
        return [str(result["harness_error"])]
    aspects = result.get("aspects") or {}
    gaps = [
        f"{aspect}: expected {want}, measured {aspects.get(aspect)!r}"
        for aspect, want in (result.get("expected_aspects") or {}).items()
        if aspects.get(aspect) != want
    ]
    identity = aspects.get("_identity") or {}
    want_identity = result.get("expected_identity_verified")
    if bool(identity.get("verified")) is not bool(want_identity):
        gaps.append(
            f"identity: expected verified={want_identity}, "
            f"measured {identity.get('verified')!r} "
            f"(unverified={identity.get('unverified')})"
        )
    return gaps


def main() -> int:
    results: list[dict[str, Any]] = []
    for engine in ENGINES:
        for fn in (scenario_create_new, scenario_bare_existing):
            try:
                results.append(fn(engine))
            except Exception as exc:  # a harness failure is a result, not a skip
                results.append(
                    {
                        "scenario": fn.__name__,
                        "engine": engine,
                        "harness_error": f"{type(exc).__name__}: {exc}"[:400],
                    }
                )
            results[-1]["gaps"] = _gaps(results[-1])
    print(json.dumps(results, indent=2, default=str))
    for r in results:
        verdict = "GAP" if r.get("gaps") else "as declared"
        print(f"{r.get('engine'):12} {r.get('scenario'):48} {verdict}")
        for gap in r.get("gaps") or []:
            print(f"             - {gap}")
    out = "/home/ubuntu/repro/structural_attestation_results.json"
    try:
        with open(out, "w", encoding="utf-8") as fh:
            json.dump(results, fh, indent=2, default=str)
        print(f"\nartifact: {out}")
    except OSError as exc:
        print(f"artifact not written: {exc}")
    return 1 if any(r.get("gaps") for r in results) else 0


if __name__ == "__main__":
    raise SystemExit(main())
