// Generated by scripts/generate_generic_sql_map.py from apps/api/connectors/generic_sql.py
// Do not edit manually; re-run the script to update.

export interface GenericSqlInfo {
  base: string;
  port: number;
}

export const GENERIC_SQL_INFO: Record<string, GenericSqlInfo> = {
  "actian": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "actian_avalanche": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "alloydb": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "amazon_athena": {
    "base": "awsathena+rest",
    "port": 443
  },
  "amazon_aurora": {
    "base": "mysql+pymysql",
    "port": 3306
  },
  "amazon_emr": {
    "base": "hive",
    "port": 10000
  },
  "amazon_rds_mysql": {
    "base": "mysql+pymysql",
    "port": 3306
  },
  "amazon_rds_oracle": {
    "base": "oracle+oracledb",
    "port": 1521
  },
  "amazon_rds_postgresql": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "amazon_rds_sql_server": {
    "base": "mssql+pyodbc",
    "port": 1433
  },
  "apache_hive": {
    "base": "hive",
    "port": 10000
  },
  "apache_impala": {
    "base": "impala",
    "port": 21000
  },
  "apache_spark": {
    "base": "spark",
    "port": 10000
  },
  "athena": {
    "base": "awsathena+rest",
    "port": 443
  },
  "azure_database_for_mysql": {
    "base": "mysql+pymysql",
    "port": 3306
  },
  "azure_database_for_postgresql": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "azure_sql_database": {
    "base": "mssql+pyodbc",
    "port": 1433
  },
  "azure_synapse": {
    "base": "mssql+pyodbc",
    "port": 1433
  },
  "azure_synapse_dedicated": {
    "base": "mssql+pyodbc",
    "port": 1433
  },
  "azure_synapse_serverless": {
    "base": "mssql+pyodbc",
    "port": 1433
  },
  "citus": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "citus_db": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "citusdb": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "clickhouse": {
    "base": "clickhouse+native",
    "port": 9000
  },
  "cloudera_data_platform": {
    "base": "impala",
    "port": 21000
  },
  "cockroachdb": {
    "base": "postgresql+psycopg2",
    "port": 26257
  },
  "cratedb": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "databricks": {
    "base": "databricks",
    "port": 443
  },
  "db2": {
    "base": "ibm_db_sa",
    "port": 50000
  },
  "doris": {
    "base": "mysql+pymysql",
    "port": 9030
  },
  "dremio": {
    "base": "dremio+flight",
    "port": 32010
  },
  "dremio_flight": {
    "base": "dremio+flight",
    "port": 32010
  },
  "druid": {
    "base": "druid",
    "port": 8082
  },
  "duckdb": {
    "base": "duckdb",
    "port": 0
  },
  "exasol": {
    "base": "exasol+pyodbc",
    "port": 8563
  },
  "firebird": {
    "base": "firebird+fdb",
    "port": 3050
  },
  "firebolt": {
    "base": "firebolt",
    "port": 443
  },
  "gaussdb": {
    "base": "mysql+pymysql",
    "port": 3306
  },
  "goldendb": {
    "base": "mysql+pymysql",
    "port": 3306
  },
  "google_cloud_sql_mysql": {
    "base": "mysql+pymysql",
    "port": 3306
  },
  "google_cloud_sql_postgresql": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "google_cloud_sql_sql_server": {
    "base": "mssql+pyodbc",
    "port": 1433
  },
  "greenplum": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "h2": {
    "base": "h2",
    "port": 9092
  },
  "hana": {
    "base": "hana",
    "port": 30015
  },
  "ibm_db2": {
    "base": "ibm_db_sa",
    "port": 50000
  },
  "ibm_db2_warehouse": {
    "base": "ibm_db_sa",
    "port": 50000
  },
  "informix": {
    "base": "informix+pyodbc",
    "port": 9088
  },
  "mariadb": {
    "base": "mysql+pymysql",
    "port": 3306
  },
  "materialize": {
    "base": "postgresql+psycopg2",
    "port": 6875
  },
  "microsoft_sql_server": {
    "base": "mssql+pyodbc",
    "port": 1433
  },
  "motherduck": {
    "base": "duckdb",
    "port": 0
  },
  "mssql": {
    "base": "mssql+pyodbc",
    "port": 1433
  },
  "mysql": {
    "base": "mysql+pymysql",
    "port": 3306
  },
  "neon": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "netezza": {
    "base": "nzpsql",
    "port": 5480
  },
  "oceanbase": {
    "base": "mysql+pymysql",
    "port": 2881
  },
  "oracle": {
    "base": "oracle+oracledb",
    "port": 1521
  },
  "oracle_autonomous_warehouse": {
    "base": "oracle+oracledb",
    "port": 1521
  },
  "oracle_db": {
    "base": "oracle+oracledb",
    "port": 1521
  },
  "phoenix": {
    "base": "phoenix",
    "port": 8765
  },
  "pinot": {
    "base": "pinot",
    "port": 8099
  },
  "planetscale": {
    "base": "mysql+pymysql",
    "port": 3306
  },
  "polardb": {
    "base": "mysql+pymysql",
    "port": 3306
  },
  "postgresql": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "presto": {
    "base": "presto",
    "port": 8080
  },
  "questdb": {
    "base": "postgresql+psycopg2",
    "port": 8812
  },
  "redshift": {
    "base": "postgresql+psycopg2",
    "port": 5439
  },
  "risingwave": {
    "base": "postgresql+psycopg2",
    "port": 4566
  },
  "sap_ase": {
    "base": "sybase+pyodbc",
    "port": 5000
  },
  "sap_bw_4hana": {
    "base": "hana",
    "port": 30015
  },
  "sap_hana": {
    "base": "hana",
    "port": 30015
  },
  "sap_iq": {
    "base": "sybase+pyodbc",
    "port": 2638
  },
  "singlestore": {
    "base": "mysql+pymysql",
    "port": 3306
  },
  "spark": {
    "base": "spark",
    "port": 10000
  },
  "sparksql": {
    "base": "spark",
    "port": 10000
  },
  "sql_server": {
    "base": "mssql+pyodbc",
    "port": 1433
  },
  "sqlite": {
    "base": "sqlite",
    "port": 0
  },
  "sqlserver": {
    "base": "mssql+pyodbc",
    "port": 1433
  },
  "starrocks": {
    "base": "mysql+pymysql",
    "port": 9030
  },
  "supabase": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "sybase_ase": {
    "base": "sybase+pyodbc",
    "port": 5000
  },
  "synapse": {
    "base": "mssql+pyodbc",
    "port": 1433
  },
  "synapse_analytics": {
    "base": "mssql+pyodbc",
    "port": 1433
  },
  "teradata": {
    "base": "teradatasql",
    "port": 1025
  },
  "teradata_vantage": {
    "base": "teradatasql",
    "port": 1025
  },
  "tidb": {
    "base": "mysql+pymysql",
    "port": 4000
  },
  "timescaledb": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "trino": {
    "base": "trino",
    "port": 8080
  },
  "vertica": {
    "base": "vertica+vertica_python",
    "port": 5433
  },
  "vitess": {
    "base": "mysql+pymysql",
    "port": 3306
  },
  "yellowbrick": {
    "base": "postgresql+psycopg2",
    "port": 5432
  },
  "yugabytedb": {
    "base": "postgresql+psycopg2",
    "port": 5433
  }
};
